/**
 * Standard house flip scenario.
 * Used for regression testing to detect calculation drift.
 */
import type { ParsedDealFormData, DealAnalysisResult } from "@/types/deal-copilot";

export const standardFlipInput: ParsedDealFormData = {
  title: "3-bed terrace, Croydon",
  purchasePrice: 350000,
  refurbBudget: 55000,
  estimatedGdv: 475000,
  rentalIncome: 1500, // £1,500/month
  holdingCosts: 8000,
  region: "London",
  propertyCondition: "Average",
};

/**
 * Expected output from deterministic engines.
 * These values must remain stable to detect calculation drift.
 *
 * Generated by running analyzeDeal(standardFlipInput) with known good engines.
 * If any value changes unexpectedly, a calculation regression has occurred.
 */
export const standardFlipExpected = {
  score: {
    ready: true,
    recommendation: "Consider" as const,
    roi: 18.9,
    estimated_profit: 62000,
    investment_score: 6.8,
    risk_level: "Low" as const,
    gross_yield: 5.1,
  },
};

/**
 * Tolerance for floating-point comparisons.
 * Engine outputs are rounded to 1 decimal place for ROI/yield.
 */
export const TOLERANCE = 0.1;

/**
 * Verify standard flip output against known expected values.
 */
export function validateStandardFlip(result: DealAnalysisResult): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!result.ready) {
    errors.push("Analysis should be ready for standard flip input");
  }

  if (
    result.roi?.roi !== undefined &&
    Math.abs(result.roi.roi - standardFlipExpected.score.roi) > TOLERANCE
  ) {
    errors.push(`ROI drift: expected ${standardFlipExpected.score.roi}%, got ${result.roi.roi}%`);
  }

  if (
    result.roi?.estimated_profit !== undefined &&
    Math.abs(result.roi.estimated_profit - standardFlipExpected.score.estimated_profit) > 1000
  ) {
    errors.push(
      `Profit drift: expected £${standardFlipExpected.score.estimated_profit}, got £${result.roi.estimated_profit}`,
    );
  }

  if (
    result.roi?.investment_score !== undefined &&
    Math.abs(result.roi.investment_score - standardFlipExpected.score.investment_score) > TOLERANCE
  ) {
    errors.push(
      `Investment score drift: expected ${standardFlipExpected.score.investment_score}/10, got ${result.roi.investment_score}/10`,
    );
  }

  if (result.score.recommendation !== standardFlipExpected.score.recommendation) {
    errors.push(
      `Recommendation drift: expected "${standardFlipExpected.score.recommendation}", got "${result.score.recommendation}"`,
    );
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
