// Backwards compatibility re-exports. Types have been extracted to @repo/types.
// Use @repo/types directly for new code.

export type {
  Profile,
  Project,
  ProjectStatus,
  NewProjectInput,
  ProjectStage,
  PropertyType,
  UKRegion,
  Photo,
  AnalysisResult,
  RoomType,
  ConditionLevel,
  RefurbLevel,
  RedesignConcept,
  RedesignStyle,
  Estimate,
  EstimateItem,
  EstimateInputs,
  EstimateCategory,
  FinishLevel,
  InvestmentMetrics,
  RiskLevel,
  Report,
  DealAddress,
  DealFinancials,
  DealId,
  DealInput,
  DealMetadata,
  DealSource,
  DealStatus,
  DealSummary,
  RiskCategory,
  RiskItem,
  RiskSourceProductId,
  RiskSummary,
  Scenario,
  ScenarioFinancials,
  ScenarioId,
  ScenarioProgramme,
  ScenarioSet,
  ScenarioSourceProductId,
  ScenarioType,
} from "@repo/types";

export {
  createDealMetadata,
  createEmptyRiskSummary,
  summariseRisks,
  getBaseScenario,
  getScenarioByType,
} from "@repo/types";
