/**
 * Maps existing enforcement / governance surfaces to status and owners.
 * Registration only.
 */
import type { RegistryStatus } from "./types";

export type EnforcementItem = {
  id: string;
  kind: "invariant" | "freeze" | "ci" | "adr" | "documentation" | "baseline";
  source: string;
  description: string;
  enforcementLevel: RegistryStatus;
  owner: string;
  status: "active" | "planned" | "interim";
};

export const ENFORCEMENT_INVENTORY: EnforcementItem[] = [
  {
    id: "inv-package-dependency",
    kind: "invariant",
    source: "tests/invariants/package-dependency.invariant.test.ts",
    description: "Packages ↛ app; domain packages ↛ React/Supabase/OpenAI",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-platform-boundary",
    kind: "invariant",
    source: "tests/invariants/platform-boundary.invariant.test.ts",
    description: "Vendor SDKs only in platform/packages",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-server-only",
    kind: "invariant",
    source: "tests/invariants/server-only-boundary.invariant.test.ts",
    description: "Server-only modules and client leak prevention",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-env",
    kind: "invariant",
    source: "tests/invariants/auth-env.invariant.test.ts",
    description: "No client-exposed service role / OpenAI VITE_ keys",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-feature-slice",
    kind: "invariant",
    source: "tests/invariants/feature-slice.invariant.test.ts",
    description: "Feature layering; domain no IO; infra no direct openai package",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-public-api",
    kind: "invariant",
    source: "tests/invariants/public-api-boundary.invariant.test.ts",
    description: "Cross-feature imports via public API",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/estimate-public-api.invariant.test.ts",
    description: "External code must not import @/features/estimate/infrastructure (Phase 9 C2)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ai-upload-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/ai-upload-public-api.invariant.test.ts",
    description: "External code must not import @/features/ai-upload/infrastructure (Phase 10B C7)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-dealchat-channel-lifecycle",
    kind: "invariant",
    source: "tests/invariants/dealchat-channel-lifecycle.invariant.test.ts",
    description:
      "Deal Copilot presentation must not own the deal_messages Realtime channel lifecycle (Phase 11C C3)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-domain-purity",
    kind: "invariant",
    source: "tests/invariants/projects-domain-purity.invariant.test.ts",
    description:
      "C4/C4c sealed: C4a domain purity (domain pure; Project types not redefined in lib) + C4c-5 projectStore retirement (no projectStore definition/import under src; lib/projects domain-only; no core→@/lib/projects reverse edge; no store-backed helpers)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-query-keys",
    kind: "invariant",
    source: "tests/invariants/projects-query-keys.invariant.test.ts",
    description:
      'C4/C4c sealed: canonical projectKeys; projectsListQueryOptions owns full list (projectKeys.all); no raw ["projects"] list keys; no ["project-catalog"] dual list; useProjectCatalog adapter only; useProject uses projectQueryOptions/byId; stage dual-cache sync; create seeds byId + exact list invalidate',
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-query-cache-lifecycle",
    kind: "invariant",
    source: "tests/invariants/auth-query-cache-lifecycle.invariant.test.ts",
    description:
      "C4c-4 sealed: root auth.onChange delegates to applyAuthQueryCacheTransition; exact AUTH_USER_QUERY_KEY preserved; non-auth cancel+remove on identity boundary; signOut not sole isolation path; no queryClient.clear (Projects list is non-auth and is purged on identity boundary)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photos-query-keys",
    kind: "invariant",
    source: "tests/invariants/photos-query-keys.invariant.test.ts",
    description:
      "C5 Completed (76cf1c8): canonical product-photo reads enforced (projectKeys.photosByProject + fetchProjectPhotosList + photosQueryOptions; usePhotos call-site; AI catalog/room-analysis on fetchProjectPhotosList; PHOTOS_TABLE_ALLOWLIST exact). Canonical writes enforced (hooks + Bulk → photos-write; Bulk direct Auth/Storage/from(photos)/photoStore/p-limit banned; allowlist write site photos-write only). React Query list-cache authority enforced. Neutral ProjectPhoto (photos-types) and formatFileSize (file-utils) enforced as pure authorities. photoStore absence, src/lib/photos.ts absence, @/lib/photos import ban, Projects photo-barrel ban, and photo-module Auth-listener ban enforced under src (lexical scans + filesystem absence). Public gallery and photo-analysis keys remain separate. Strength: lexical/source-path (comment-stripped), not full AST.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-favorites-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-favorites-presentation.invariant.test.ts",
    description:
      "AO-1B1 Completed (322156a): TradepersonCard direct Supabase access prohibited; direct Auth resolution (auth.getUser) prohibited; direct trade_favorites writes prohibited; component must call useToggleTradeFavorite; write authority src/lib/marketplace-write.ts; read authority src/lib/queries/marketplace.ts; favorites cache authority React Query marketplaceKeys.favoritesByUser; canonical mutation orchestration useToggleTradeFavorite. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim full marketplace, MessagingInbox, or AO-1 presentation debt resolved.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-quote-request-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-quote-request-presentation.invariant.test.ts",
    description:
      "AO-1B2 Completed (fcc13b6): QuoteRequestDialog direct Supabase access prohibited; direct Auth resolution (auth.getUser) prohibited; direct QueryClient/invalidateQueries ownership prohibited; component must call useCreateQuoteRequest; write authority src/lib/marketplace-write.ts createQuoteRequest; read authority src/lib/queries/marketplace.ts; mutation and invalidation authority useCreateQuoteRequest; query-key authority marketplaceKeys.quoteRequestsByProject; automatic mutation retry disabled; no optimistic create. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim MessagingInbox, Realtime, or full AO-1 presentation debt resolved.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-message-send-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-message-send-presentation.invariant.test.ts",
    description:
      "AO-1B3.1 Completed (fa12ccc): MessagingInbox direct trade_messages insert prohibited; legacy Auth resolution (auth.getUser) prohibited; send-owned useMutation prohibited; component must call useSendTradeMessage and resolveTradeMessageRecipient; write authority src/lib/marketplace-write.ts sendTradeMessage; read authority src/lib/queries/marketplace.ts; message-send mutation and send invalidation authority useSendTradeMessage (marketplaceKeys.messagesByQuote; retry:false); recipient derivation authority resolveTradeMessageRecipient. Realtime ownership sealed separately by AO-1B3.2 (inv-marketplace-messaging-realtime-presentation). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim messaging fully migrated, schema drift resolved, recipient profile-ID semantics corrected, AST-level enforcement, AO-1B3 complete, or AO-1 complete.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-messaging-realtime-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-messaging-realtime-presentation.invariant.test.ts",
    description:
      "AO-1B3.2 Completed (d407cc6): MessagingInbox direct Supabase client access prohibited; direct channel lifecycle (channel/removeChannel/postgres_changes) prohibited; direct useQueryClient ownership prohibited; component must call useTradeMessagesRealtime; Realtime lifecycle and Realtime invalidation authority src/features/marketplace/presentation/hooks/useTradeMessagesRealtime.ts (marketplaceKeys.messagesByQuote); trade_messages write authority src/lib/marketplace-write.ts; trade_messages read authority src/lib/queries/marketplace.ts; send mutation and send invalidation authority useSendTradeMessage; recipient authority resolveTradeMessageRecipient; component public contract projectId?: string. Send presentation invariant active (inv-marketplace-message-send-presentation; AO-1B3.1 Completed at fa12ccc). Realtime presentation invariant active. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all presentation infrastructure removed app-wide, MessagingInbox owns no queries, schema drift resolved, recipient profile-ID semantics corrected, or AST/semantic enforcement.",

    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photo-analysis-viewer-write-presentation",
    kind: "invariant",
    source: "tests/invariants/photo-analysis-viewer-write-presentation.invariant.test.ts",
    description:
      "AO-1C1 Completed at 0802bcc: PhotoAnalysisViewer direct photo_analysis_results UPDATE prohibited; direct Supabase ownership for edit write prohibited; component-owned edit useMutation prohibited; component must call useUpdatePhotoAnalysisResult. photo_analysis_results read authority: src/lib/queries/photo-analysis.ts. photo_analysis_results UPDATE authority: src/lib/photo-analysis-write.ts (updatePhotoAnalysisResult). analysis edit mutation and optimistic-cache authority: useUpdatePhotoAnalysisResult (photoAnalysisByProjectQueryOptions(projectId).queryKey; retry:false; cancel/snapshot/patch/rollback; success-only invalidation). edit UI authority (toasts/dialog/pending): PhotoAnalysisViewer. Apply-to-Estimate estimate-cache authority sealed separately by AO-1C2 (inv-photo-analysis-viewer-apply-estimate-presentation). room/category quirk preserved intentionally (UI room; persisted category from newData.category). public component contract: projectId, photos, analyses. presentation invariant active. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all photo infrastructure migrated, room/category behaviour corrected, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photo-analysis-viewer-apply-estimate-presentation",
    kind: "invariant",
    source: "tests/invariants/photo-analysis-viewer-apply-estimate-presentation.invariant.test.ts",
    description:
      "AO-1C2 Completed at fe28f25: PhotoAnalysisViewer direct QueryClient ownership prohibited; direct estimate cache read/write/invalidation (getQueryData/setQueryData/invalidateQueries) prohibited; direct estimateQueryOptions ownership prohibited; component must call useApplyPhotoAnalysesToEstimate. Apply-to-Estimate cache authority: useApplyPhotoAnalysesToEstimate (estimateQueryOptions(projectId).queryKey / projectKeys.estimateByProject; append-only rooms; write-before-void-invalidate; no useMutation; no toast; no Auth/Supabase). analysis-to-estimate mapping authority: mapPhotoAnalysesToEstimateRooms. estimate query-key authority: estimateQueryOptions / projectKeys.estimateByProject. Apply UI, selected-row resolution, empty guard, toasts, and selection: PhotoAnalysisViewer. photo-analysis edit authority: useUpdatePhotoAnalysisResult (AO-1C1 Completed at 0802bcc). estimate database-save authority: unchanged outside AO-1C2 (EstimateBuilder / saveAIEstimate). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all estimate infrastructure migrated, dual estimate query keys unified, room-name dedupe, EstimateBuilder save ownership migrated, FloorplanViewer cache ownership migrated, room/category behaviour corrected, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-admin-metrics-presentation",
    kind: "invariant",
    source: "tests/invariants/admin-metrics-presentation.invariant.test.ts",
    description:
      "AO-1D1 Completed at d3cab3f: admin route platform Supabase ownership prohibited; direct .from reads prohibited; retired inline loadPlatformStats/loadRecentProjects/loadUsers prohibited; component must call useAdminPlatformStats, useAdminRecentProjects, and useAdminUsers. Read authority: src/features/admin/infrastructure/adminMetricsRead.ts — fetchAdminPlatformStats (R1–R3), fetchAdminRecentProjects (R4), fetchAdminUsers (R5); exact R1–R5; soft PostgREST failures; Promise.all for stats. Query-key authority: adminKeys. Query options: three independent admin*QueryOptions (retry false; no focus/reconnect refetch; staleTime Infinity). Hook authority: useAdminPlatformStats, useAdminRecentProjects, useAdminUsers (three independent useQuery). Admin presentation: src/routes/_authed/admin.tsx. Access control remains RequireAdmin and parent _authed boundary (unchanged; out of slice). AIMetricsDashboard remains local diagnostics (unchanged; out of slice). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all admin infrastructure migrated, all admin Auth ownership migrated, all dashboard reads migrated, all presentation infrastructure migrated, all project/profile reads owned by admin feature, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-dashboard-onboarding-auth-presentation",
    kind: "invariant",
    source: "tests/invariants/dashboard-onboarding-auth-presentation.invariant.test.ts",
    description:
      "AO-1D2 Completed at 9b4da54: dashboard direct platform Supabase Auth ownership prohibited; direct supabase.auth prohibited; direct auth.updateUser prohibited; route-owned onboarding_goal Auth payload prohibited; component must call useOnboardingGoalSelection. Auth metadata mirror authority: src/features/auth/infrastructure/updateAuthOnboardingGoal.ts (updateAuthOnboardingGoal; payload { data: { onboarding_goal } } only; returned errors uninspected). Onboarding selection orchestration: useOnboardingGoalSelection (local write first; state before Auth await; empty skips Auth; silent thrown Auth failures; no useMutation/QueryClient/session refresh/profile refetch). Onboarding localStorage authority: onboardingStorage.ts. Dashboard presentation: src/routes/_authed/dashboard.tsx. Current-user display: useAuth. Parent authentication: _authed route boundary (unchanged). New-user onboarding-card consume: dashboard route plus onboardingStorage. First-study state: hasCompletedFirstStudy plus dashboard route state. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all dashboard infrastructure migrated, all dashboard Auth ownership migrated, AuthExperience migrated, auth callback migrated, all authentication presentation debt migrated, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-password-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-password-presentation.invariant.test.ts",
    description:
      "AO-1E1.1 Completed at 8bdf817: AuthExperience direct password sign-in (signInWithPassword) prohibited; direct password signup (supabase.auth.signUp) prohibited; password-flow AUTH_USER_QUERY_KEY seed, fromSupabaseUser, markNewUserOnboarding, identifyAnalyticsUser, and trackSignupCompleted prohibited in component; component must call useAuthPasswordCredentials. Password sign-in Auth authority: signInWithPasswordEmail (raw email/password; throw returned errors). Password signup Auth authority: signUpWithPasswordEmail (full_name/company_name only; no emailRedirectTo; throw returned errors). Password credential orchestration, AUTH_USER_QUERY_KEY seed, fromSupabaseUser mapping, password-flow analytics, and session-present onboarding flag: useAuthPasswordCredentials (+ onboardingStorage for mark). Sign-in/signup validation, lockout, toast, and application navigation: AuthExperience. OAuth extracted under AO-1E1.2 (inv-auth-experience-oauth-presentation). Email-access (magic link / password recovery) extracted under AO-1E1.3 (inv-auth-experience-email-access-presentation). Auth callback separate surface. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, AO-1E1 complete, AuthExperience fully presentation-only for all Auth operations, auth callback migrated, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-oauth-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-oauth-presentation.invariant.test.ts",
    description:
      "AO-1E1.2 Completed at ce4384a: AuthExperience direct signInWithOAuth prohibited; OAuth initiation analytics prohibited in component; component must call useOAuthSignIn. Google and Apple OAuth Auth authority: startOAuthSignIn (providers google|apple only; redirectTo + queryParams; throw returned errors; no window/analytics). OAuth initiation orchestration: useOAuthSignIn (callback URL ${origin}/auth/callback; redirect_to forwarding without initiation validation; oauth_sign_in_initiated before Auth). Provider loading (oauthLoading/appleLoading; success leaves true; formDisabled omits appleLoading), logger, provider-facing error copy, and provider buttons: AuthExperience. Browser redirect: Supabase Auth SDK. OAuth code exchange, session/AUTH_USER_QUERY_KEY seed, redirect_to validation, and post-callback navigation: auth_.callback.tsx (out of slice). Residual OTP extracted under AO-1E1.3. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, AO-1E1 complete, AuthExperience fully presentation-only for all Auth operations, auth callback migrated, AST/semantic enforcement, or Supabase Preview success.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-email-access-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-email-access-presentation.invariant.test.ts",
    description:
      "AO-1E1.3 Completed at ba442e3: AuthExperience direct signInWithOtp prohibited; direct password-reset request (resetPasswordForEmail) prohibited; direct recovery-session password update (legacy auth.updatePassword) prohibited; platform Supabase browser import prohibited in AuthExperience; @/lib/auth import prohibited in AuthExperience; component must call useAuthEmailAccess. Magic-link Auth authority: sendMagicLinkEmail (signInWithOtp; email + emailRedirectTo; throw returned errors). Password-reset request Auth authority: requestPasswordResetEmail (resetPasswordForEmail; email + redirectTo; throw returned errors). Recovery-session password-update Auth authority: updateAuthUserPassword (updateUser password only; throw returned errors). Email-access orchestration: useAuthEmailAccess (magic callback ${origin}/auth/callback; truthy redirect → redirect_to via URLSearchParams; falsy → no redirect_to; recovery ${origin}/auth/callback?type=recovery; rethrows). Validation, loading (magicLinkLoading/forgotPasswordLoading/submitting; formDisabled omits appleLoading), logger, user-facing error copy, success toasts, and reset success navigation: AuthExperience. Magic-link completion (code exchange, cache seed, redirect_to validation/navigation) and recovery callback routing: auth_.callback.tsx (out of slice; further extracted under AO-1F1). src/lib/auth.ts helpers may remain for other legacy consumers. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, callback migrated, src/lib/auth removed, all repository Auth infrastructure migrated, all AuthExperience presentation logic removed, reset validation corrected, forgot-password redirect forwarding corrected, callback cache seed corrected, AST/semantic enforcement, or Supabase Preview success.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-callback-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-callback-presentation.invariant.test.ts",
    description:
      "AO-1F1 Completed at 68a3eb7: auth_.callback route direct exchangeCodeForSession prohibited; direct getSession prohibited; direct QueryClient mutation prohibited; direct AUTH_USER_QUERY_KEY ownership prohibited; direct fromSupabaseUser mapping prohibited; platform Supabase browser import prohibited; @/lib/auth import prohibited; useQueryClient prohibited; direct success navigation (useNavigate) prohibited; component must call useAuthCallbackCompletion. Code-exchange Auth authority: exchangeAuthCode (exchangeCodeForSession(code); throw returned errors; return { user }). No-code browser-session Auth authority: getBrowserAuthSession (getSession; session user or null; ignore returned error field; rejections propagate). Callback orchestration: completeAuthCallback (urlError → error_description ?? error; no-code session; code exchange; recovery; map via fromSupabaseUser; destination resolve; no QC/nav). Destination resolution: resolveAuthCallbackDestination (startsWith('/') ? redirectTo : '/dashboard'; preserves protocol-relative and /auth acceptance as adjacent debt). Auth-user mapper: fromSupabaseUser through application layer. Auth-user query key: AUTH_USER_QUERY_KEY from @/hooks/useAuth. Cache seeding and normal success navigation: useAuthCallbackCompletion (setQueryData before navigate). Recovery navigation: useAuthCallbackCompletion (/auth?mode=reset replace true; no seed). Route retains: zod search validation, effect entry, loading Completing sign in…, error Authentication failed + back link, error state. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, protocol-relative redirects fixed, callback redirect unified with AuthExperience, recovery cache seed added, getSession rejection fixed, callback idempotency added, src/lib/auth removed, AuthProvider migrated, all Auth architecture complete, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-builder-save-presentation",
    kind: "invariant",
    source: "tests/invariants/estimate-builder-save-presentation.invariant.test.ts",
    description:
      "AO-1G1 Completed at 2e77407: EstimateBuilder direct useMutation prohibited; direct useQueryClient prohibited; direct saveAIEstimate prohibited; direct getQueryData/setQueryData/cancelQueries/invalidateQueries prohibited; direct estimateQueryOptions/projectKeys ownership prohibited; component must call useSaveEstimateBuilder and buildEstimateBuilderSaveInput. Save-input mapping authority: buildEstimateBuilderSaveInput (pure; exact title/region/notes/vat_rate/item zeros/is_ai_suggested false; totals passed through). Manual-save mutation + product estimate cache authority: useSaveEstimateBuilder (saveAIEstimate; estimateQueryOptions / projectKeys.estimateByProject optimistic write+rollback; financialsByProject invalidation; draft localStorage clear; toasts Estimate saved / Save failed; onSaved; one-shot getSeededEstimate; no room-estimate key). Persistence authority: saveAIEstimate (unchanged insert-only). Product estimate query-key authority: estimateQueryOptions / projectKeys.estimateByProject. Optimistic cache authority: useSaveEstimateBuilder onMutate. Rollback authority: useSaveEstimateBuilder onError (truthy previous). Estimate and financials invalidation, save toasts, draft clear, onSaved: useSaveEstimateBuilder onSuccess. EstimateBuilder retains: editor state, calculations, PDF, dialogs, save trigger and button UI. Dual estimate keys preserved; AI room-estimate path unchanged (useSaveAIEstimate / AIEstimateBuilder out of slice). Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, dual estimate query keys unified, AIEstimateBuilder migrated, repository AI flags corrected, draft write restored, contingency column persisted, entire estimate subsystem migrated, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-floorplan-viewer-persistence-presentation",
    kind: "invariant",
    source: "tests/invariants/floorplan-viewer-persistence-presentation.invariant.test.ts",
    description:
      "AO-1H1 Completed at b97654d: FloorplanViewer direct auth.getUser for writes prohibited; direct platform Supabase and floorplan table writes prohibited; direct persistence useMutation prohibited; direct uploadFloorplanModel/deleteFloorplanStorage orchestration prohibited; direct floorplanKeys ownership prohibited; component must call useFloorplanViewerMutations from @/features/floorplan. Model/annotation/measurement write authority: floorplanWrite primitives (floorplan_models insert select/single + delete by id; floorplan_annotations insert + delete by id; floorplan_measurements insert with measurement_type + delete by id; throw Supabase errors unchanged; no Auth/React/QC/toast/logger/Storage). Write Auth + Storage orchestration + six mutations + floorplan/annotation/measurement/Refresh invalidations + mutation toasts + upload logger + isUploading: useFloorplanViewerMutations (mutation-time auth.getUser for creates only; exact missing-user strings; Storage helpers remain @/lib/floorplan). FloorplanViewer retains: read query factories, selected-model state, editor modes, scene, dialogs, exports, validation, estimate read. Estimate tag sync: useSyncFloorplanTagsToEstimate (AO-1H2). room-estimate and financials untouched. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, dual estimate keys unified, Storage/database atomicity fixed, optimistic floorplan rows, AST/semantic enforcement, or Supabase Preview success.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-floorplan-viewer-estimate-sync-presentation",
    kind: "invariant",
    source: "tests/invariants/floorplan-viewer-estimate-sync-presentation.invariant.test.ts",
    description:
      "AO-1H2 Completed at 6bde476: FloorplanViewer direct useQueryClient prohibited; direct product-estimate getQueryData prohibited; direct product-estimate setQueryData prohibited; direct product-estimate invalidateQueries prohibited; inline estimate tag-sync ownership (inline syncTagsToEstimate body) prohibited; component must call useSyncFloorplanTagsToEstimate from @/features/floorplan and pass annotations. Estimate tag mapping authority: mapFloorplanAnnotationsToEstimateRooms (pure; unique Set first-seen; typeof string && !!label; no trim; case-sensitive exact name compare; id fp-${now()}-${label} with now once per new room; shape {id,name,items:[]}). Estimate tag-sync presentation authority: useSyncFloorplanTagsToEstimate (product estimate key estimateQueryOptions(projectId).queryKey → [projects, projectId, estimate]; cache strategy get→set→fire-and-forget invalidate; sync info + success toasts; silent empty annotations/labels; no useMutation/pending; no room-estimate; no financials; no saveAIEstimate; estimate persistence none in this flow). FloorplanViewer retains: sync trigger, estimate read query (useQuery(estimateQueryOptions)), floorplan read queries, scene, dialogs, exports, validation, H1 mutations hook (AO-1H1 persistence boundary retained). room-estimate untouched; financials untouched; dual estimate keys preserved. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, estimate read extracted, placeholder rooms persisted, query keys consolidated, financials synchronised, room-estimate synchronised, cold-cache overwrite risk resolved, double-click race resolved, AST/semantic enforcement, or all estimate architecture complete.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-bulk-photo-upload-queryclient-presentation",
    kind: "invariant",
    source: "tests/invariants/bulk-photo-upload-queryclient-presentation.invariant.test.ts",
    description:
      "AO-1I1 Completed at 0f07376: BulkPhotoUpload direct QueryClient prohibited; direct project-photo invalidation (invalidateQueries) prohibited; direct photo query-key ownership (projectKeys.photosByProject) prohibited; direct getQueryData/setQueryData/cancelQueries/removeQueries/resetQueries prohibited; raw [projects, projectId, photos] literals prohibited; deep hook imports prohibited; component must call useInvalidateProjectPhotos( from @/features/ai-upload. Canonical invalidation authority: useInvalidateProjectPhotos. Photo-list query-key authority: projectKeys.photosByProject / photosQueryOptions. Invalidation mode: fire-and-forget. Full-success invalidation: once after completed item patches. Partial-success invalidation: once when successes.length > 0. Zero-success and unknown-error invalidation: none. Upload primitive: uploadProjectPhotos, unchanged (C5). BulkPhotoUpload retains: selection, validation, batch orchestration, concurrency 3, progress, processing guard, success/failure item patches, toasts, rendering. Storage/database ownership: photos-write primitives. C5 boundary retained. Legacy project-query edge retired; legacy photos-write and photos-types edges retained. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim all BulkPhotoUpload orchestration extracted, all photo architecture complete, all legacy photo edges removed, query factories migrated, upload persistence redesigned, retry/cancellation/optimistic photo rows, AST/semantic enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-deal-chat-mutation-queryclient-presentation",
    kind: "invariant",
    source: "tests/invariants/deal-chat-mutation-queryclient-presentation.invariant.test.ts",
    description:
      "AO-1J1 Completed at fd1b964: DealChat direct useMutation prohibited; direct mutation-oriented QueryClient prohibited; direct cancelQueries/getQueryData/setQueryData/invalidateQueries/removeQueries/resetQueries prohibited; DealChat inline dealChatKeys prohibited; raw deal-threads/deal-messages key literals prohibited; deep presentation-hook imports prohibited; component must call useSendDealChatMessage, useCreateDealThread, useInvalidateDealMessages from @/core/dealCopilot/presentation and retain useDealMessagesChannel. Canonical key authority: dealChatKeys. Canonical send authority: useSendDealChatMessage (awaited cancel; snapshot; opt-${Date.now()} user append; success strip opt-* + append user+assistant; rollback prev; deal_message_sent; no send invalidation). Canonical create-thread authority: useCreateDealThread (createThreadServerFn; threads key once fire-and-forget; onCreated; deal_thread_created). Canonical realtime invalidation callback: useInvalidateDealMessages (void fire-and-forget). Optimistic send lifecycle: useSendDealChatMessage. Realtime channel lifecycle: useDealMessagesChannel (C3). DealChat retains: thread and message reads, draft state, voice input, thread selection, submit wiring, pending/error display, message rendering, scroll behaviour, C3 realtime hook. Server transport: serverFns/dealChat. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim all DealChat architecture complete, read queries migrated, realtime redesigned, AI generation redesigned, streaming/retry/cancel-generation implemented, realtime race fixed, deduplication redesigned, schema changed, AST/semantic enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-query-key-authority",
    kind: "invariant",
    source: "tests/invariants/estimate-query-key-authority.invariant.test.ts",
    description:
      "AO-1K1 Completed at 8fce9bc: Canonical estimate query-key authority: projectKeys.estimateByProject. Canonical estimate query-options authority: estimateQueryOptions. Canonical tuple: [projects, projectId, estimate]. Canonical query function: getLatestRoomEstimate. Raw room-estimate production key: prohibited. Raw canonical tuple recreation in estimate hooks: prohibited. Local duplicate estimate key factories: prohibited. useRoomEstimate: canonical estimateQueryOptions. AI estimate save invalidation: canonical estimate key (projectKeys.estimateByProject). AI financials invalidation: projectKeys.financialsByProject. Invalidation semantics: success-only, fire-and-forget, non-exact, project-scoped (estimate before financials). Manual estimate save: unchanged. SSR and route prefetch: unchanged. Product estimate readers: unchanged. Project isolation: preserved. AIEstimateBuilder save ownership: unchanged and deferred. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string/split-literal bypasses remain possible). Does not claim all estimate architecture complete, estimate keys moved into feature ownership, getLatestProjectEstimate unified, AIEstimateBuilder save ownership extracted, pricing redesigned, persistence redesigned, dependency debt resolved, Supabase Preview succeeded, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ai-estimate-builder-save-presentation",
    kind: "invariant",
    source: "tests/invariants/ai-estimate-builder-save-presentation.invariant.test.ts",
    description:
      "AO-1L1 Completed at f316c53: AIEstimateBuilder save orchestration: useAIEstimateBuilderSave from @/features/estimate. Save-input authority: buildAIEstimateBuilderSaveInput (pure; exact title/region/notes/vat_rate 20/calculateLineItem/totals passthrough). Mutation authority: useSaveAIEstimate. Repository authority: saveAIEstimate. Estimate invalidation: useSaveAIEstimate (projectKeys.estimateByProject). Financials invalidation: useSaveAIEstimate (projectKeys.financialsByProject). Direct component useSaveAIEstimate: prohibited. Direct component save.mutate: prohibited. Direct component useMutation: prohibited. Direct component QueryClient: prohibited. Direct component payload construction (SaveAIEstimateInput/vat_rate:20/AI Estimate title template): prohibited. Direct component repository save import: prohibited. Direct orchestration-hook QueryClient/projectKeys/repository import/useMutation/invalidateQueries/room-estimate: prohibited. Generation: component-owned and unchanged (useGenerateEstimate). Pricing preview: component-owned and unchanged. AO-1K1 Completed and preserved (canonical estimate key; production room-estimate 0; estimate→financials success-only void non-exact). Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim all AIEstimateBuilder architecture complete, generation extracted, pricing redesigned, optimistic AI save introduced, repository ownership changed, AO-1K1 changed, dependency debt resolved, Supabase Preview succeeded, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-pitch-deck-generator-persistence-presentation",
    kind: "invariant",
    source: "tests/invariants/pitch-deck-generator-persistence-presentation.invariant.test.ts",
    description:
      "AO-1M2 Completed at 806cdbe: PitchDeckGenerator UI: component (props, trigger variants, button chrome, progress UI, disabled state, hook invocation). Pitch-deck orchestration: useGenerateAndSavePitchDeck from @/features/export. Pitch-deck data acquisition: useGenerateAndSavePitchDeck using canonical query factories. Pitch-deck PDF authority: legacyPdfExporter / generatePitchDeckPDF. Pitch-deck persistence: supabaseExportRepository → savePitchDeckToSupabase. Pitch-deck history invalidation: useGenerateAndSavePitchDeck (pitchDecksByProjectQueryOptions [projects, projectId, pitchDecks] after successful save only, awaited, non-exact, no optimistic writes). Direct component QueryClient: prohibited. Direct component query-factory orchestration: prohibited. Direct component auth.getUser: prohibited. Direct component PDF orchestration: prohibited. Direct component persistence helper: prohibited. Direct component Supabase: prohibited. Direct hook Supabase/storage/table access: prohibited. Direct hook savePitchDeckToSupabase: prohibited. Canonical pitch-deck key: [projects, projectId, pitchDecks]. AO-1K1 estimate key: [projects, projectId, estimate] via estimateQueryOptions; production room-estimate 0. AO-1 remains Active. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim server-side PDF generation, server-side pitch-deck upload, all export architecture complete, all AO-1M1 residuals resolved, public-share security completed, dependency debt resolved, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-gallery-publish-mutation-presentation",
    kind: "invariant",
    source: "tests/invariants/gallery-publish-mutation-presentation.invariant.test.ts",
    description:
      "AO-1M3 Completed at 409eb037: Gallery publish UI: PublishToGallery (form, title/description trim, public/featured toggles, cover upload, gallery/leads reads, public URL, statistics, mutate callbacks, success/error toasts, pending/disabled UI). Gallery mutation lifecycle: useUpsertGalleryProject from @/features/gallery. Gallery mutation cache authority: useUpsertGalleryProject using galleryKeys.byProject → [projects, projectId, gallery] (cancelQueries + optimistic setQueryData + onError restore previous + onSettled invalidateQueries non-exact; success and failure; no public-list/by-ID invalidation). Gallery persistence: galleryRepository.upsertGalleryProject (browser Supabase public_gallery_projects upsert onConflict project_id; select(*).single(); payload project_id/created_by/slug=projectId + fields + title ?? Untitled Project; error log + rethrow). Gallery table: public_gallery_projects. Conflict target: project_id. Canonical gallery key: [projects, projectId, gallery]. Direct component useMutation: prohibited. Direct component QueryClient mutation lifecycle: prohibited. Direct component Supabase gallery upsert: prohibited. Direct component transitional gallery hook (@/hooks/useGallery): prohibited. Direct presentation-hook Supabase access: prohibited. Direct transitional src/hooks gallery mutation: removed. Gallery reads: unchanged query factories. Cover-image upload: unchanged and outside AO-1M3 (PublishToGallery + uploadGalleryCoverImage). AO-1 remains Active. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim cover-upload extraction, gallery read migration, server-side publish, public gallery cache redesign complete, schema/RLS redesign, all AO-1 residuals complete, dependency debt resolved, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-project-stage-mutation-presentation",
    kind: "invariant",
    source: "tests/invariants/project-stage-mutation-presentation.invariant.test.ts",
    description:
      "AO-1M4 Completed at 5107f2ec: Project-stage consumers: the four project workflow routes (upload/analysis/estimate/report). Project-stage public API: @/features/projects. Project-stage mutation lifecycle: useSetProjectStage. Project-stage persistence: projectStageRepository.setProjectStageDone. Project table: projects. Stage fields: photos_done, analysis_done, estimate_done, report_done. Canonical cache keys: projectKeys.all + projectKeys.byId(projectId). Dual-cache helpers: applyProjectStageOptimistic + restoreProjectStageCaches (exact cancelQueries both keys; no invalidateQueries/onSuccess/onSettled; no seed of absent list/detail). Direct route stage-mutation infrastructure: prohibited. Direct route repository access: prohibited. Direct route Supabase projects update: prohibited. Direct presentation-hook Supabase access: prohibited. Transitional useSetProjectStage authority: removed from src/hooks/useProjects.ts (file retained for reads/create/progress). Project reads, creation and progress: unchanged. Route bans: useSetProjectStage from @/hooks/useProjects, useMutation, setQueryData, cancelQueries, from(projects), platform supabase, projectStageRepository. Hook bans: platform supabase, from(projects), .update(, invalidateQueries, toast, logger, auth.getUser. Hook requirements: useMutation, useQueryClient, projectKeys, applyProjectStageOptimistic, restoreProjectStageCaches, setProjectStageDone. C4c-3 dual-cache helpers remain in src/lib/queries/projects.ts. AO-1 remains Active. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim project create extraction, list/detail read migration, stage state machine, server-side stage mutation, schema/RLS redesign, all AO-1 residuals complete, dependency debt resolved, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-deal-opportunity-update-presentation",
    kind: "invariant",
    source: "tests/invariants/deal-opportunity-update-presentation.invariant.test.ts",
    description:
      'AO-1M5 Completed at fd769094: Deal-opportunity update consumer: edit opportunity route (deal-copilot/$opportunityId.edit). Public API: @/features/deal-copilot. Mutation lifecycle: useUpdateOpportunity. Persistence: dealOpportunityRepository.updateOpportunity. Table: deal_opportunities. Operation: update by opportunity ID with selected single-row return. Return: DealOpportunity. Field mapping: camelCase domain patch to snake_case database patch (title, listingUrl→listing_url, postcode, propertyType→property_type, bedrooms, purchasePrice→purchase_price, estimatedGdv→estimated_gdv, expectedMonthlyRent→expected_monthly_rent, refurbBudget→refurb_budget, targetExitStrategy→target_exit_strategy, status; undefined omitted; zero/null preserved). Timestamp: updated_at generated for every update. Cache key: literal ["opportunities"]. Cache lifecycle: success-only invalidateQueries (not exact; no failure invalidation). Optimistic update: none. Rollback: none. Authentication: implicit browser session. Ownership: deal-opportunity owner RLS. Direct route update infrastructure: prohibited. Direct route repository access: prohibited. Direct presentation-hook Supabase access: prohibited. Transitional useUpdateOpportunity: removed from src/hooks/useOpportunities.ts (file retained for list/detail/save/delete). Dead store update authority: removed (opportunityStore.update and updateDealOpportunity export). Route bans: useUpdateOpportunity from @/hooks/useOpportunities, useMutation, useQueryClient, setQueryData, cancelQueries, from(deal_opportunities), platform supabase, dealOpportunityRepository, analyzeDealServerFn. Hook bans: platform supabase, from(deal_opportunities), .update(, auth.getUser, setQueryData, cancelQueries, onMutate, toast, logger, navigation. Hook requirements: useMutation, useQueryClient, invalidateQueries, repository updateOpportunity. Repository requirements: deal_opportunities, update, eq id, select, single, updated_at + field maps; bans user_id filter, upsert, insert, auth, RQ, toast, logger. DealAnalysisCard: outside AO-1M5 and reserved for AO-1M6. AO-1 remains Active. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim all opportunity mutations migrated, opportunity reads/save/delete migrated, opportunity store retired, query-key factory introduced, optimistic updates introduced, DealAnalysisCard migrated, schema/RLS redesigned, dependency debt resolved, AST enforcement, or AO-1 Completed.',
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-deal-analysis-card-mutation-presentation",
    kind: "invariant",
    source: "tests/invariants/deal-analysis-card-mutation-presentation.invariant.test.ts",
    description:
      "AO-1M6 Completed at e9d374c: Deal analysis consumer: DealAnalysisCard. Feature public API: @/features/deal-copilot (useAnalyzeDealOpportunity + AnalyzeDealOpportunityVariables; retains useUpdateOpportunity + UpdateOpportunityVariables). Mutation lifecycle: useAnalyzeDealOpportunity. Server transport: analyzeDealServerFn (unchanged path src/serverFns/dealAnalysis.ts). Server authority: Zod validation (required opportunityId, optional promptContext), requireUser, per-user deal-analysis rate limit, server Supabase deal_opportunities SELECT eq id single, RLS ownership enforcement, dynamic runDealAnalysis, DealAnalysis return. Analysis authority: runDealAnalysis adapter (OpenAI gpt-4o, json_object, temperature 0.3, max tokens 1500, 45s timeout, dealAnalysisSchema, development mock without key outside production, production missing-key throw, server logger and Sentry). Persistence: none (no analysis write). Database access: server-side opportunity SELECT only. Analysis state: React Query mutation data/error/pending only. Product QueryClient lifecycle: none (no useQueryClient, invalidateQueries, setQueryData, analysis query keys, or opportunity invalidation). Trigger: explicit button click only. Success analytics: trackEvent(deal_analyzed) once with no payload. Failure analytics: none. Direct component useMutation: prohibited. Direct component server-function access: prohibited. Direct component deal_analyzed analytics: prohibited. Direct hook browser Supabase: prohibited. Direct hook QueryClient operations: prohibited. Public server-function export from feature API: prohibited. DealIntakeForm deterministic analyzeDeal: outside AO-1M6. AO-1M6 Completed at e9d374c. AO-1 remains Active. Enforcement: progressive lexical seal (comment-stripped source scan; alias/dynamic-import/wrapper/computed-string bypasses remain possible). Does not claim AI redesign, provider/prompt/model/timeout/fallback change, analysis persistence, query-key topology, server function relocation, deterministic intake migration, opportunity reads, shell auth cleanup, dependency debt resolved, AST enforcement, or AO-1 Completed.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "migration-register",

    kind: "documentation",
    source: "tests/invariants/config/migration-register.ts",
    description: "Living migration candidate register + architecture objectives",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-legacy-freeze",
    kind: "freeze",
    source: "tests/invariants/legacy-layer-freeze.invariant.test.ts",
    description:
      "No new files under src/lib/hooks/services outside allowlists (allowlists consumed from config/frozen-path-allowlists.ts)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-no-legacy-imports",
    kind: "baseline",
    source: "tests/invariants/no-legacy-imports.invariant.test.ts",
    description:
      "Ratchet: new @/core|lib|services|integrations edges fail; baseline from config/legacy-import-baseline.ts; stale edges fail",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/architecture-registry.invariant.test.ts",
    description: "Registry integrity + structured exception governance fields",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "cfg-structured-exceptions",
    kind: "baseline",
    source: "tests/invariants/config/exceptions.ts",
    description: "Structured freeze + legacy-import + ui-migration exceptions (Phase 3)",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-routes",
    kind: "invariant",
    source: "tests/invariants/routes.invariant.test.ts",
    description: "Route file existence and docs alignment",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-shim-cleanup",
    kind: "invariant",
    source: "tests/invariants/shim-cleanup.invariant.test.ts",
    description: "Deleted AI shims stay gone",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ui-migration",
    kind: "invariant",
    source: "tests/invariants/ui-migration.invariant.test.ts",
    description: "UI package migration rules + known exceptions",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-pricing",
    kind: "invariant",
    source: "tests/invariants/pricing.invariant.test.ts",
    description: "Pricing engine contract / authority",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-pricing-authority",
    kind: "invariant",
    source: "tests/invariants/pricing-authority.test.ts",
    description: "ROI consumes pricing.mid_total only",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-scoring",
    kind: "invariant",
    source: "tests/invariants/scoring.invariant.test.ts",
    description: "Deal scoring determinism",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-deal-score",
    kind: "invariant",
    source: "tests/invariants/dealScore.test.ts",
    description: "Deal score shape and regressions",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-estimator-engines",
    kind: "invariant",
    source: "tests/invariants/estimator-engines.invariant.test.ts",
    description: "Estimator engine contracts",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "ci-main",
    kind: "ci",
    source: ".github/workflows/ci.yml",
    description: "typecheck, lint, build:vercel + test:invariants job",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "ci-security",
    kind: "ci",
    source: ".github/workflows/security.yml",
    description: "Security workflow",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "adr-0001",
    kind: "adr",
    source: "docs/architecture/adr/0001-adopt-rules-first-incremental-architecture-governance.md",
    description: "Rules-first incremental governance decision",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-overview",
    kind: "documentation",
    source: "docs/architecture/overview.md",
    description: "Authoritative architecture policy",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-phase-0",
    kind: "documentation",
    source: "docs/architecture/phase-0-inventory-report.md",
    description: "Verified inventory evidence",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-2-3",
    kind: "documentation",
    source: "tests/invariants/config/",
    description:
      "Architecture registry: ownership/deps + freeze/baseline path sets consumed by freezes & no-legacy-imports",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-4-data",
    kind: "documentation",
    source: "tests/invariants/config/data/",
    description:
      "Data architecture registry: domains, tenancy, tables, storage, lineage, security (registration only)",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-data-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/data-architecture-registry.invariant.test.ts",
    description:
      "Data registry integrity + ratchets: tables↔types, domains, buckets, migrations, authority flags, enforcement evidence",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "planned-product-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Product isolation Genius ↔ IQ; products ↛ Deal Copilot internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
  {
    id: "planned-deal-copilot-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Deal Copilot multi-root isolation from direct Supabase / product internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
];
