/**
 * Maps existing enforcement / governance surfaces to status and owners.
 * Registration only.
 */
import type { RegistryStatus } from "./types";

export type EnforcementItem = {
  id: string;
  kind: "invariant" | "freeze" | "ci" | "adr" | "documentation" | "baseline";
  source: string;
  description: string;
  enforcementLevel: RegistryStatus;
  owner: string;
  status: "active" | "planned" | "interim";
};

export const ENFORCEMENT_INVENTORY: EnforcementItem[] = [
  {
    id: "inv-package-dependency",
    kind: "invariant",
    source: "tests/invariants/package-dependency.invariant.test.ts",
    description: "Packages ↛ app; domain packages ↛ React/Supabase/OpenAI",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-platform-boundary",
    kind: "invariant",
    source: "tests/invariants/platform-boundary.invariant.test.ts",
    description: "Vendor SDKs only in platform/packages",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-server-only",
    kind: "invariant",
    source: "tests/invariants/server-only-boundary.invariant.test.ts",
    description: "Server-only modules and client leak prevention",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-env",
    kind: "invariant",
    source: "tests/invariants/auth-env.invariant.test.ts",
    description: "No client-exposed service role / OpenAI VITE_ keys",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-feature-slice",
    kind: "invariant",
    source: "tests/invariants/feature-slice.invariant.test.ts",
    description: "Feature layering; domain no IO; infra no direct openai package",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-public-api",
    kind: "invariant",
    source: "tests/invariants/public-api-boundary.invariant.test.ts",
    description: "Cross-feature imports via public API",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/estimate-public-api.invariant.test.ts",
    description: "External code must not import @/features/estimate/infrastructure (Phase 9 C2)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ai-upload-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/ai-upload-public-api.invariant.test.ts",
    description: "External code must not import @/features/ai-upload/infrastructure (Phase 10B C7)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-dealchat-channel-lifecycle",
    kind: "invariant",
    source: "tests/invariants/dealchat-channel-lifecycle.invariant.test.ts",
    description:
      "Deal Copilot presentation must not own the deal_messages Realtime channel lifecycle (Phase 11C C3)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-domain-purity",
    kind: "invariant",
    source: "tests/invariants/projects-domain-purity.invariant.test.ts",
    description:
      "C4/C4c sealed: C4a domain purity (domain pure; Project types not redefined in lib) + C4c-5 projectStore retirement (no projectStore definition/import under src; lib/projects domain-only; no core→@/lib/projects reverse edge; no store-backed helpers)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-query-keys",
    kind: "invariant",
    source: "tests/invariants/projects-query-keys.invariant.test.ts",
    description:
      'C4/C4c sealed: canonical projectKeys; projectsListQueryOptions owns full list (projectKeys.all); no raw ["projects"] list keys; no ["project-catalog"] dual list; useProjectCatalog adapter only; useProject uses projectQueryOptions/byId; stage dual-cache sync; create seeds byId + exact list invalidate',
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-query-cache-lifecycle",
    kind: "invariant",
    source: "tests/invariants/auth-query-cache-lifecycle.invariant.test.ts",
    description:
      "C4c-4 sealed: root auth.onChange delegates to applyAuthQueryCacheTransition; exact AUTH_USER_QUERY_KEY preserved; non-auth cancel+remove on identity boundary; signOut not sole isolation path; no queryClient.clear (Projects list is non-auth and is purged on identity boundary)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photos-query-keys",
    kind: "invariant",
    source: "tests/invariants/photos-query-keys.invariant.test.ts",
    description:
      "C5 Completed (76cf1c8): canonical product-photo reads enforced (projectKeys.photosByProject + fetchProjectPhotosList + photosQueryOptions; usePhotos call-site; AI catalog/room-analysis on fetchProjectPhotosList; PHOTOS_TABLE_ALLOWLIST exact). Canonical writes enforced (hooks + Bulk → photos-write; Bulk direct Auth/Storage/from(photos)/photoStore/p-limit banned; allowlist write site photos-write only). React Query list-cache authority enforced. Neutral ProjectPhoto (photos-types) and formatFileSize (file-utils) enforced as pure authorities. photoStore absence, src/lib/photos.ts absence, @/lib/photos import ban, Projects photo-barrel ban, and photo-module Auth-listener ban enforced under src (lexical scans + filesystem absence). Public gallery and photo-analysis keys remain separate. Strength: lexical/source-path (comment-stripped), not full AST.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-favorites-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-favorites-presentation.invariant.test.ts",
    description:
      "AO-1B1 Completed (322156a): TradepersonCard direct Supabase access prohibited; direct Auth resolution (auth.getUser) prohibited; direct trade_favorites writes prohibited; component must call useToggleTradeFavorite; write authority src/lib/marketplace-write.ts; read authority src/lib/queries/marketplace.ts; favorites cache authority React Query marketplaceKeys.favoritesByUser; canonical mutation orchestration useToggleTradeFavorite. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim full marketplace, MessagingInbox, or AO-1 presentation debt resolved.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-quote-request-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-quote-request-presentation.invariant.test.ts",
    description:
      "AO-1B2 Completed (fcc13b6): QuoteRequestDialog direct Supabase access prohibited; direct Auth resolution (auth.getUser) prohibited; direct QueryClient/invalidateQueries ownership prohibited; component must call useCreateQuoteRequest; write authority src/lib/marketplace-write.ts createQuoteRequest; read authority src/lib/queries/marketplace.ts; mutation and invalidation authority useCreateQuoteRequest; query-key authority marketplaceKeys.quoteRequestsByProject; automatic mutation retry disabled; no optimistic create. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim MessagingInbox, Realtime, or full AO-1 presentation debt resolved.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-message-send-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-message-send-presentation.invariant.test.ts",
    description:
      "AO-1B3.1 Completed (fa12ccc): MessagingInbox direct trade_messages insert prohibited; legacy Auth resolution (auth.getUser) prohibited; send-owned useMutation prohibited; component must call useSendTradeMessage and resolveTradeMessageRecipient; write authority src/lib/marketplace-write.ts sendTradeMessage; read authority src/lib/queries/marketplace.ts; message-send mutation and send invalidation authority useSendTradeMessage (marketplaceKeys.messagesByQuote; retry:false); recipient derivation authority resolveTradeMessageRecipient. Realtime ownership sealed separately by AO-1B3.2 (inv-marketplace-messaging-realtime-presentation). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim messaging fully migrated, schema drift resolved, recipient profile-ID semantics corrected, AST-level enforcement, AO-1B3 complete, or AO-1 complete.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-marketplace-messaging-realtime-presentation",
    kind: "invariant",
    source: "tests/invariants/marketplace-messaging-realtime-presentation.invariant.test.ts",
    description:
      "AO-1B3.2 Completed (d407cc6): MessagingInbox direct Supabase client access prohibited; direct channel lifecycle (channel/removeChannel/postgres_changes) prohibited; direct useQueryClient ownership prohibited; component must call useTradeMessagesRealtime; Realtime lifecycle and Realtime invalidation authority src/features/marketplace/presentation/hooks/useTradeMessagesRealtime.ts (marketplaceKeys.messagesByQuote); trade_messages write authority src/lib/marketplace-write.ts; trade_messages read authority src/lib/queries/marketplace.ts; send mutation and send invalidation authority useSendTradeMessage; recipient authority resolveTradeMessageRecipient; component public contract projectId?: string. Send presentation invariant active (inv-marketplace-message-send-presentation; AO-1B3.1 Completed at fa12ccc). Realtime presentation invariant active. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all presentation infrastructure removed app-wide, MessagingInbox owns no queries, schema drift resolved, recipient profile-ID semantics corrected, or AST/semantic enforcement.",

    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photo-analysis-viewer-write-presentation",
    kind: "invariant",
    source: "tests/invariants/photo-analysis-viewer-write-presentation.invariant.test.ts",
    description:
      "AO-1C1 Completed at 0802bcc: PhotoAnalysisViewer direct photo_analysis_results UPDATE prohibited; direct Supabase ownership for edit write prohibited; component-owned edit useMutation prohibited; component must call useUpdatePhotoAnalysisResult. photo_analysis_results read authority: src/lib/queries/photo-analysis.ts. photo_analysis_results UPDATE authority: src/lib/photo-analysis-write.ts (updatePhotoAnalysisResult). analysis edit mutation and optimistic-cache authority: useUpdatePhotoAnalysisResult (photoAnalysisByProjectQueryOptions(projectId).queryKey; retry:false; cancel/snapshot/patch/rollback; success-only invalidation). edit UI authority (toasts/dialog/pending): PhotoAnalysisViewer. Apply-to-Estimate estimate-cache authority sealed separately by AO-1C2 (inv-photo-analysis-viewer-apply-estimate-presentation). room/category quirk preserved intentionally (UI room; persisted category from newData.category). public component contract: projectId, photos, analyses. presentation invariant active. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all photo infrastructure migrated, room/category behaviour corrected, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photo-analysis-viewer-apply-estimate-presentation",
    kind: "invariant",
    source: "tests/invariants/photo-analysis-viewer-apply-estimate-presentation.invariant.test.ts",
    description:
      "AO-1C2 Completed at fe28f25: PhotoAnalysisViewer direct QueryClient ownership prohibited; direct estimate cache read/write/invalidation (getQueryData/setQueryData/invalidateQueries) prohibited; direct estimateQueryOptions ownership prohibited; component must call useApplyPhotoAnalysesToEstimate. Apply-to-Estimate cache authority: useApplyPhotoAnalysesToEstimate (estimateQueryOptions(projectId).queryKey / projectKeys.estimateByProject; append-only rooms; write-before-void-invalidate; no useMutation; no toast; no Auth/Supabase). analysis-to-estimate mapping authority: mapPhotoAnalysesToEstimateRooms. estimate query-key authority: estimateQueryOptions / projectKeys.estimateByProject. Apply UI, selected-row resolution, empty guard, toasts, and selection: PhotoAnalysisViewer. photo-analysis edit authority: useUpdatePhotoAnalysisResult (AO-1C1 Completed at 0802bcc). estimate database-save authority: unchanged outside AO-1C2 (EstimateBuilder / saveAIEstimate). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all estimate infrastructure migrated, dual estimate query keys unified, room-name dedupe, EstimateBuilder save ownership migrated, FloorplanViewer cache ownership migrated, room/category behaviour corrected, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-admin-metrics-presentation",
    kind: "invariant",
    source: "tests/invariants/admin-metrics-presentation.invariant.test.ts",
    description:
      "AO-1D1 Completed at d3cab3f: admin route platform Supabase ownership prohibited; direct .from reads prohibited; retired inline loadPlatformStats/loadRecentProjects/loadUsers prohibited; component must call useAdminPlatformStats, useAdminRecentProjects, and useAdminUsers. Read authority: src/features/admin/infrastructure/adminMetricsRead.ts — fetchAdminPlatformStats (R1–R3), fetchAdminRecentProjects (R4), fetchAdminUsers (R5); exact R1–R5; soft PostgREST failures; Promise.all for stats. Query-key authority: adminKeys. Query options: three independent admin*QueryOptions (retry false; no focus/reconnect refetch; staleTime Infinity). Hook authority: useAdminPlatformStats, useAdminRecentProjects, useAdminUsers (three independent useQuery). Admin presentation: src/routes/_authed/admin.tsx. Access control remains RequireAdmin and parent _authed boundary (unchanged; out of slice). AIMetricsDashboard remains local diagnostics (unchanged; out of slice). Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all admin infrastructure migrated, all admin Auth ownership migrated, all dashboard reads migrated, all presentation infrastructure migrated, all project/profile reads owned by admin feature, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-dashboard-onboarding-auth-presentation",
    kind: "invariant",
    source: "tests/invariants/dashboard-onboarding-auth-presentation.invariant.test.ts",
    description:
      "AO-1D2 Completed at 9b4da54: dashboard direct platform Supabase Auth ownership prohibited; direct supabase.auth prohibited; direct auth.updateUser prohibited; route-owned onboarding_goal Auth payload prohibited; component must call useOnboardingGoalSelection. Auth metadata mirror authority: src/features/auth/infrastructure/updateAuthOnboardingGoal.ts (updateAuthOnboardingGoal; payload { data: { onboarding_goal } } only; returned errors uninspected). Onboarding selection orchestration: useOnboardingGoalSelection (local write first; state before Auth await; empty skips Auth; silent thrown Auth failures; no useMutation/QueryClient/session refresh/profile refetch). Onboarding localStorage authority: onboardingStorage.ts. Dashboard presentation: src/routes/_authed/dashboard.tsx. Current-user display: useAuth. Parent authentication: _authed route boundary (unchanged). New-user onboarding-card consume: dashboard route plus onboardingStorage. First-study state: hasCompletedFirstStudy plus dashboard route state. Strength: lexical (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, all dashboard infrastructure migrated, all dashboard Auth ownership migrated, AuthExperience migrated, auth callback migrated, all authentication presentation debt migrated, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-password-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-password-presentation.invariant.test.ts",
    description:
      "AO-1E1.1 Completed at 8bdf817: AuthExperience direct password sign-in (signInWithPassword) prohibited; direct password signup (supabase.auth.signUp) prohibited; password-flow AUTH_USER_QUERY_KEY seed, fromSupabaseUser, markNewUserOnboarding, identifyAnalyticsUser, and trackSignupCompleted prohibited in component; component must call useAuthPasswordCredentials. Password sign-in Auth authority: signInWithPasswordEmail (raw email/password; throw returned errors). Password signup Auth authority: signUpWithPasswordEmail (full_name/company_name only; no emailRedirectTo; throw returned errors). Password credential orchestration, AUTH_USER_QUERY_KEY seed, fromSupabaseUser mapping, password-flow analytics, and session-present onboarding flag: useAuthPasswordCredentials (+ onboardingStorage for mark). Sign-in/signup validation, lockout, toast, and application navigation: AuthExperience. OAuth extracted under AO-1E1.2 (inv-auth-experience-oauth-presentation). Email-access (magic link / password recovery) extracted under AO-1E1.3 (inv-auth-experience-email-access-presentation). Auth callback separate surface. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, AO-1E1 complete, AuthExperience fully presentation-only for all Auth operations, auth callback migrated, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-oauth-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-oauth-presentation.invariant.test.ts",
    description:
      "AO-1E1.2 Completed at ce4384a: AuthExperience direct signInWithOAuth prohibited; OAuth initiation analytics prohibited in component; component must call useOAuthSignIn. Google and Apple OAuth Auth authority: startOAuthSignIn (providers google|apple only; redirectTo + queryParams; throw returned errors; no window/analytics). OAuth initiation orchestration: useOAuthSignIn (callback URL ${origin}/auth/callback; redirect_to forwarding without initiation validation; oauth_sign_in_initiated before Auth). Provider loading (oauthLoading/appleLoading; success leaves true; formDisabled omits appleLoading), logger, provider-facing error copy, and provider buttons: AuthExperience. Browser redirect: Supabase Auth SDK. OAuth code exchange, session/AUTH_USER_QUERY_KEY seed, redirect_to validation, and post-callback navigation: auth_.callback.tsx (out of slice). Residual OTP extracted under AO-1E1.3. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, AO-1E1 complete, AuthExperience fully presentation-only for all Auth operations, auth callback migrated, AST/semantic enforcement, or Supabase Preview success.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-experience-email-access-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-experience-email-access-presentation.invariant.test.ts",
    description:
      "AO-1E1.3 Completed at ba442e3: AuthExperience direct signInWithOtp prohibited; direct password-reset request (resetPasswordForEmail) prohibited; direct recovery-session password update (legacy auth.updatePassword) prohibited; platform Supabase browser import prohibited in AuthExperience; @/lib/auth import prohibited in AuthExperience; component must call useAuthEmailAccess. Magic-link Auth authority: sendMagicLinkEmail (signInWithOtp; email + emailRedirectTo; throw returned errors). Password-reset request Auth authority: requestPasswordResetEmail (resetPasswordForEmail; email + redirectTo; throw returned errors). Recovery-session password-update Auth authority: updateAuthUserPassword (updateUser password only; throw returned errors). Email-access orchestration: useAuthEmailAccess (magic callback ${origin}/auth/callback; truthy redirect → redirect_to via URLSearchParams; falsy → no redirect_to; recovery ${origin}/auth/callback?type=recovery; rethrows). Validation, loading (magicLinkLoading/forgotPasswordLoading/submitting; formDisabled omits appleLoading), logger, user-facing error copy, success toasts, and reset success navigation: AuthExperience. Magic-link completion (code exchange, cache seed, redirect_to validation/navigation) and recovery callback routing: auth_.callback.tsx (out of slice; further extracted under AO-1F1). src/lib/auth.ts helpers may remain for other legacy consumers. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, callback migrated, src/lib/auth removed, all repository Auth infrastructure migrated, all AuthExperience presentation logic removed, reset validation corrected, forgot-password redirect forwarding corrected, callback cache seed corrected, AST/semantic enforcement, or Supabase Preview success.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-callback-presentation",
    kind: "invariant",
    source: "tests/invariants/auth-callback-presentation.invariant.test.ts",
    description:
      "AO-1F1 Completed at 68a3eb7: auth_.callback route direct exchangeCodeForSession prohibited; direct getSession prohibited; direct QueryClient mutation prohibited; direct AUTH_USER_QUERY_KEY ownership prohibited; direct fromSupabaseUser mapping prohibited; platform Supabase browser import prohibited; @/lib/auth import prohibited; useQueryClient prohibited; direct success navigation (useNavigate) prohibited; component must call useAuthCallbackCompletion. Code-exchange Auth authority: exchangeAuthCode (exchangeCodeForSession(code); throw returned errors; return { user }). No-code browser-session Auth authority: getBrowserAuthSession (getSession; session user or null; ignore returned error field; rejections propagate). Callback orchestration: completeAuthCallback (urlError → error_description ?? error; no-code session; code exchange; recovery; map via fromSupabaseUser; destination resolve; no QC/nav). Destination resolution: resolveAuthCallbackDestination (startsWith('/') ? redirectTo : '/dashboard'; preserves protocol-relative and /auth acceptance as adjacent debt). Auth-user mapper: fromSupabaseUser through application layer. Auth-user query key: AUTH_USER_QUERY_KEY from @/hooks/useAuth. Cache seeding and normal success navigation: useAuthCallbackCompletion (setQueryData before navigate). Recovery navigation: useAuthCallbackCompletion (/auth?mode=reset replace true; no seed). Route retains: zod search validation, effect entry, loading Completing sign in…, error Authentication failed + back link, error state. Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, protocol-relative redirects fixed, callback redirect unified with AuthExperience, recovery cache seed added, getSession rejection fixed, callback idempotency added, src/lib/auth removed, AuthProvider migrated, all Auth architecture complete, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-builder-save-presentation",
    kind: "invariant",
    source: "tests/invariants/estimate-builder-save-presentation.invariant.test.ts",
    description:
      "AO-1G1 In Progress: EstimateBuilder direct useMutation prohibited; direct useQueryClient prohibited; direct saveAIEstimate prohibited; direct getQueryData/setQueryData/cancelQueries/invalidateQueries prohibited; direct estimateQueryOptions/projectKeys ownership prohibited; component must call useSaveEstimateBuilder and buildEstimateBuilderSaveInput. Save-input mapping authority: buildEstimateBuilderSaveInput (pure; exact title/region/notes/vat_rate/item zeros/is_ai_suggested false). Manual-save mutation + product estimate cache authority: useSaveEstimateBuilder (saveAIEstimate; estimateQueryOptions / projectKeys.estimateByProject optimistic write+rollback; financialsByProject invalidation; draft localStorage clear; toasts Estimate saved / Save failed; onSaved; one-shot getSeededEstimate; no room-estimate key). Persistence authority: saveAIEstimate (unchanged insert-only). Product estimate query-key authority: estimateQueryOptions / projectKeys.estimateByProject. Editor calculations, room/item CRUD, drag-and-drop, PDF export toast/logger: EstimateBuilder. AIEstimateBuilder / useSaveAIEstimate / room-estimate key unchanged (dual-key debt deferred). Strength: progressive lexical seal (comment-stripped source scan; alias/dynamic-import bypasses remain possible). Does not claim AO-1 complete, dual estimate query keys unified, AIEstimateBuilder migrated, repository AI flags corrected, draft write restored, contingency column persisted, or AST/semantic enforcement.",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "migration-register",
    kind: "documentation",
    source: "tests/invariants/config/migration-register.ts",
    description: "Living migration candidate register + architecture objectives",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-legacy-freeze",
    kind: "freeze",
    source: "tests/invariants/legacy-layer-freeze.invariant.test.ts",
    description:
      "No new files under src/lib/hooks/services outside allowlists (allowlists consumed from config/frozen-path-allowlists.ts)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-no-legacy-imports",
    kind: "baseline",
    source: "tests/invariants/no-legacy-imports.invariant.test.ts",
    description:
      "Ratchet: new @/core|lib|services|integrations edges fail; baseline from config/legacy-import-baseline.ts; stale edges fail",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/architecture-registry.invariant.test.ts",
    description: "Registry integrity + structured exception governance fields",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "cfg-structured-exceptions",
    kind: "baseline",
    source: "tests/invariants/config/exceptions.ts",
    description: "Structured freeze + legacy-import + ui-migration exceptions (Phase 3)",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-routes",
    kind: "invariant",
    source: "tests/invariants/routes.invariant.test.ts",
    description: "Route file existence and docs alignment",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-shim-cleanup",
    kind: "invariant",
    source: "tests/invariants/shim-cleanup.invariant.test.ts",
    description: "Deleted AI shims stay gone",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ui-migration",
    kind: "invariant",
    source: "tests/invariants/ui-migration.invariant.test.ts",
    description: "UI package migration rules + known exceptions",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-pricing",
    kind: "invariant",
    source: "tests/invariants/pricing.invariant.test.ts",
    description: "Pricing engine contract / authority",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-pricing-authority",
    kind: "invariant",
    source: "tests/invariants/pricing-authority.test.ts",
    description: "ROI consumes pricing.mid_total only",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-scoring",
    kind: "invariant",
    source: "tests/invariants/scoring.invariant.test.ts",
    description: "Deal scoring determinism",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-deal-score",
    kind: "invariant",
    source: "tests/invariants/dealScore.test.ts",
    description: "Deal score shape and regressions",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-estimator-engines",
    kind: "invariant",
    source: "tests/invariants/estimator-engines.invariant.test.ts",
    description: "Estimator engine contracts",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "ci-main",
    kind: "ci",
    source: ".github/workflows/ci.yml",
    description: "typecheck, lint, build:vercel + test:invariants job",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "ci-security",
    kind: "ci",
    source: ".github/workflows/security.yml",
    description: "Security workflow",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "adr-0001",
    kind: "adr",
    source: "docs/architecture/adr/0001-adopt-rules-first-incremental-architecture-governance.md",
    description: "Rules-first incremental governance decision",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-overview",
    kind: "documentation",
    source: "docs/architecture/overview.md",
    description: "Authoritative architecture policy",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-phase-0",
    kind: "documentation",
    source: "docs/architecture/phase-0-inventory-report.md",
    description: "Verified inventory evidence",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-2-3",
    kind: "documentation",
    source: "tests/invariants/config/",
    description:
      "Architecture registry: ownership/deps + freeze/baseline path sets consumed by freezes & no-legacy-imports",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-4-data",
    kind: "documentation",
    source: "tests/invariants/config/data/",
    description:
      "Data architecture registry: domains, tenancy, tables, storage, lineage, security (registration only)",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-data-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/data-architecture-registry.invariant.test.ts",
    description:
      "Data registry integrity + ratchets: tables↔types, domains, buckets, migrations, authority flags, enforcement evidence",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "planned-product-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Product isolation Genius ↔ IQ; products ↛ Deal Copilot internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
  {
    id: "planned-deal-copilot-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Deal Copilot multi-root isolation from direct Supabase / product internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
];
