/**
 * Maps existing enforcement / governance surfaces to status and owners.
 * Registration only.
 */
import type { RegistryStatus } from "./types";

export type EnforcementItem = {
  id: string;
  kind: "invariant" | "freeze" | "ci" | "adr" | "documentation" | "baseline";
  source: string;
  description: string;
  enforcementLevel: RegistryStatus;
  owner: string;
  status: "active" | "planned" | "interim";
};

export const ENFORCEMENT_INVENTORY: EnforcementItem[] = [
  {
    id: "inv-package-dependency",
    kind: "invariant",
    source: "tests/invariants/package-dependency.invariant.test.ts",
    description: "Packages ↛ app; domain packages ↛ React/Supabase/OpenAI",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-platform-boundary",
    kind: "invariant",
    source: "tests/invariants/platform-boundary.invariant.test.ts",
    description: "Vendor SDKs only in platform/packages",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-server-only",
    kind: "invariant",
    source: "tests/invariants/server-only-boundary.invariant.test.ts",
    description: "Server-only modules and client leak prevention",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-env",
    kind: "invariant",
    source: "tests/invariants/auth-env.invariant.test.ts",
    description: "No client-exposed service role / OpenAI VITE_ keys",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-feature-slice",
    kind: "invariant",
    source: "tests/invariants/feature-slice.invariant.test.ts",
    description: "Feature layering; domain no IO; infra no direct openai package",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-public-api",
    kind: "invariant",
    source: "tests/invariants/public-api-boundary.invariant.test.ts",
    description: "Cross-feature imports via public API",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-estimate-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/estimate-public-api.invariant.test.ts",
    description: "External code must not import @/features/estimate/infrastructure (Phase 9 C2)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ai-upload-public-api-seal",
    kind: "invariant",
    source: "tests/invariants/ai-upload-public-api.invariant.test.ts",
    description: "External code must not import @/features/ai-upload/infrastructure (Phase 10B C7)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-dealchat-channel-lifecycle",
    kind: "invariant",
    source: "tests/invariants/dealchat-channel-lifecycle.invariant.test.ts",
    description:
      "Deal Copilot presentation must not own the deal_messages Realtime channel lifecycle (Phase 11C C3)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-domain-purity",
    kind: "invariant",
    source: "tests/invariants/projects-domain-purity.invariant.test.ts",
    description:
      "C4/C4c sealed: C4a domain purity (domain pure; Project types not redefined in lib) + C4c-5 projectStore retirement (no projectStore definition/import under src; lib/projects domain-only; no core→@/lib/projects reverse edge; no store-backed helpers)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-projects-query-keys",
    kind: "invariant",
    source: "tests/invariants/projects-query-keys.invariant.test.ts",
    description:
      'C4/C4c sealed: canonical projectKeys; projectsListQueryOptions owns full list (projectKeys.all); no raw ["projects"] list keys; no ["project-catalog"] dual list; useProjectCatalog adapter only; useProject uses projectQueryOptions/byId; stage dual-cache sync; create seeds byId + exact list invalidate',
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-auth-query-cache-lifecycle",
    kind: "invariant",
    source: "tests/invariants/auth-query-cache-lifecycle.invariant.test.ts",
    description:
      "C4c-4 sealed: root auth.onChange delegates to applyAuthQueryCacheTransition; exact AUTH_USER_QUERY_KEY preserved; non-auth cancel+remove on identity boundary; signOut not sole isolation path; no queryClient.clear (Projects list is non-auth and is purged on identity boundary)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-photos-query-keys",
    kind: "invariant",
    source: "tests/invariants/photos-query-keys.invariant.test.ts",
    description:
      "C5-1/C5-2/C5-3B2/C5-3B3: one canonical authenticated product-photo list key (projectKeys.photosByProject); fetchProjectPhotosList + photosQueryOptions own the list fetch; usePhotos must call photosQueryOptions(); AI catalog + room-analysis mock source reads must call fetchProjectPhotosList; zero production photoStore.list outside store definition; hook writers and BulkPhotoUpload use uploadProjectPhotos/removeProjectPhoto from photos-write; BulkPhotoUpload banned from direct Auth/Storage/from(photos)/photoStore/p-limit; BulkPhotoUpload removed from photos-table allowlist; active production project-photo write call sites converged on photos-write; src/lib/photos.ts remains temporary dormant-definition exception (zero production callers); photoStore retirement deferred to C5-4; public gallery and photo-analysis keys remain separate; does not claim photoStore removal or C5 completion",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "migration-register",
    kind: "documentation",
    source: "tests/invariants/config/migration-register.ts",
    description: "Living migration candidate register + architecture objectives",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-legacy-freeze",
    kind: "freeze",
    source: "tests/invariants/legacy-layer-freeze.invariant.test.ts",
    description:
      "No new files under src/lib/hooks/services outside allowlists (allowlists consumed from config/frozen-path-allowlists.ts)",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-no-legacy-imports",
    kind: "baseline",
    source: "tests/invariants/no-legacy-imports.invariant.test.ts",
    description:
      "Ratchet: new @/core|lib|services|integrations edges fail; baseline from config/legacy-import-baseline.ts; stale edges fail",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/architecture-registry.invariant.test.ts",
    description: "Registry integrity + structured exception governance fields",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "cfg-structured-exceptions",
    kind: "baseline",
    source: "tests/invariants/config/exceptions.ts",
    description: "Structured freeze + legacy-import + ui-migration exceptions (Phase 3)",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-routes",
    kind: "invariant",
    source: "tests/invariants/routes.invariant.test.ts",
    description: "Route file existence and docs alignment",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-shim-cleanup",
    kind: "invariant",
    source: "tests/invariants/shim-cleanup.invariant.test.ts",
    description: "Deleted AI shims stay gone",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-ui-migration",
    kind: "invariant",
    source: "tests/invariants/ui-migration.invariant.test.ts",
    description: "UI package migration rules + known exceptions",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-pricing",
    kind: "invariant",
    source: "tests/invariants/pricing.invariant.test.ts",
    description: "Pricing engine contract / authority",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-pricing-authority",
    kind: "invariant",
    source: "tests/invariants/pricing-authority.test.ts",
    description: "ROI consumes pricing.mid_total only",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-scoring",
    kind: "invariant",
    source: "tests/invariants/scoring.invariant.test.ts",
    description: "Deal scoring determinism",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-deal-score",
    kind: "invariant",
    source: "tests/invariants/dealScore.test.ts",
    description: "Deal score shape and regressions",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "inv-estimator-engines",
    kind: "invariant",
    source: "tests/invariants/estimator-engines.invariant.test.ts",
    description: "Estimator engine contracts",
    enforcementLevel: "enforced",
    owner: "domain engines",
    status: "active",
  },
  {
    id: "ci-main",
    kind: "ci",
    source: ".github/workflows/ci.yml",
    description: "typecheck, lint, build:vercel + test:invariants job",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "ci-security",
    kind: "ci",
    source: ".github/workflows/security.yml",
    description: "Security workflow",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "adr-0001",
    kind: "adr",
    source: "docs/architecture/adr/0001-adopt-rules-first-incremental-architecture-governance.md",
    description: "Rules-first incremental governance decision",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-overview",
    kind: "documentation",
    source: "docs/architecture/overview.md",
    description: "Authoritative architecture policy",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "doc-phase-0",
    kind: "documentation",
    source: "docs/architecture/phase-0-inventory-report.md",
    description: "Verified inventory evidence",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-2-3",
    kind: "documentation",
    source: "tests/invariants/config/",
    description:
      "Architecture registry: ownership/deps + freeze/baseline path sets consumed by freezes & no-legacy-imports",
    enforcementLevel: "partial",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "registry-phase-4-data",
    kind: "documentation",
    source: "tests/invariants/config/data/",
    description:
      "Data architecture registry: domains, tenancy, tables, storage, lineage, security (registration only)",
    enforcementLevel: "documented",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "inv-data-architecture-registry",
    kind: "invariant",
    source: "tests/invariants/data-architecture-registry.invariant.test.ts",
    description:
      "Data registry integrity + ratchets: tables↔types, domains, buckets, migrations, authority flags, enforcement evidence",
    enforcementLevel: "enforced",
    owner: "platform architecture",
    status: "active",
  },
  {
    id: "planned-product-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Product isolation Genius ↔ IQ; products ↛ Deal Copilot internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
  {
    id: "planned-deal-copilot-isolation",
    kind: "invariant",
    source: "(not implemented)",
    description: "Deal Copilot multi-root isolation from direct Supabase / product internals",
    enforcementLevel: "planned",
    owner: "platform architecture",
    status: "planned",
  },
];
