import { createFileRoute } from "@tanstack/react-router";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/Navbar";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      {
        name: "description",
        content: "Terms of service for Refurb Genius — please read before using our platform.",
      },
      {
        property: "og:title",
        content: "Terms of Service — Refurb Genius",
      },
    ],
  }),
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="py-8 px-4 sm:px-6 md:px-8">
        <div className="mx-auto max-w-4xl">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: June 2026</p>
          </div>

          {/* Content */}
          <div className="space-y-8 text-foreground">
            {/* About Us */}
            <section>
              <h2 className="text-2xl font-semibold">1. About Us & These Terms</h2>
              <p className="mt-3 text-sm leading-relaxed">
                Refurb Genius ("the Platform") is operated by Rissolol Ltd ("we," "us," or "our"), a
                company registered in England and Wales (company number: [to be completed]),
                registered office [registered office address — to be completed]. You can contact us
                at support@refurbgenius.co.uk.
              </p>
              <p className="mt-3 text-sm leading-relaxed">
                By accessing or using the Platform, you agree to be bound by these Terms of Service
                ("Terms"). If you do not agree, you may not use the Platform. We may modify these
                Terms from time to time; where changes are material we will give you reasonable
                notice, and your continued use after the changes take effect constitutes acceptance.
                Nothing in these Terms affects your statutory rights.
              </p>
            </section>

            {/* Service Basis */}
            <section>
              <h2 className="text-2xl font-semibold">2. The Service</h2>
              <p className="mt-3 text-sm leading-relaxed">
                Refurb Genius is an AI-assisted tool that helps UK property investors analyse
                refurbishment scope and indicative costs, and model investment metrics. We provide
                the Platform with reasonable care and skill. From time to time we may add, change,
                or remove features, and we may carry out maintenance that temporarily affects
                availability. We will aim to give reasonable notice of significant changes where we
                can.
              </p>
            </section>

            {/* No Financial Advice */}
            <section>
              <h2 className="text-2xl font-semibold">3. No Financial Advice</h2>
              <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="text-sm text-red-900 font-semibold">
                  IMPORTANT: Refurb Genius does NOT provide financial, investment, legal, tax, or
                  surveying advice.
                </p>
              </div>

              <p className="mt-3 text-sm leading-relaxed">
                All estimates, projections, and recommendations generated by Refurb Genius —
                including ROI calculations, yield estimates, profit forecasts, and investment scores
                — are:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Approximate and based on simplified models</li>
                <li>• For informational and planning purposes only</li>
                <li>• Not guarantees of actual financial outcomes</li>
                <li>• Not a substitute for professional financial, legal, or accounting advice</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>You must:</strong>
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Verify all estimates independently with qualified professionals</li>
                <li>• Conduct due diligence on all properties before investment</li>
                <li>• Consult a qualified financial adviser before making investment decisions</li>
                <li>
                  • Account for market conditions, tax implications, and personal circumstances
                </li>
              </ul>
            </section>

            {/* Estimates & Projections */}
            <section>
              <h2 className="text-2xl font-semibold">4. Refurbishment Estimates & Projections</h2>

              <h3 className="mt-5 text-lg font-medium">Estimates Are Approximate</h3>
              <p className="mt-2 text-sm leading-relaxed">
                Refurbishment cost estimates are generated using:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Regional cost multipliers based on historical data</li>
                <li>• Property condition assessments (which may contain errors)</li>
                <li>• Simplified finish-level assumptions</li>
                <li>• Industry-average material and labour costs</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>These estimates may differ significantly from actual quotes.</strong> Always
                obtain competitive quotes from suitably qualified contractors before committing to a
                project.
              </p>

              <h3 className="mt-5 text-lg font-medium">ROI & Yield Disclaimers</h3>
              <p className="mt-2 text-sm leading-relaxed">
                ROI, yield, and profit projections do not account for:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Taxes, stamp duty, or transaction costs</li>
                <li>• Maintenance reserves or void periods</li>
                <li>• Interest rates or financing costs</li>
                <li>• Tenant demand or local rental market volatility</li>
                <li>• Regulatory changes (environmental, rental, planning)</li>
                <li>• Force majeure or unforeseen circumstances</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Use at Your Own Risk</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You acknowledge that you use these estimates at your own risk. We strongly recommend
                obtaining professional valuations, surveys, and financial analysis before making any
                investment decision.
              </p>
            </section>

            {/* AI Output Advisory */}
            <section>
              <h2 className="text-2xl font-semibold">5. AI-Generated Content & Analysis</h2>

              <h3 className="mt-5 text-lg font-medium">Accuracy of AI Analysis</h3>
              <p className="mt-2 text-sm leading-relaxed">
                AI-generated analyses (photo interpretation, design suggestions, condition
                assessments) are produced by machine-learning models and may contain:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Misidentifications or incorrect room categorisations</li>
                <li>• Overstated or understated condition severity</li>
                <li>• Irrelevant or impractical design suggestions</li>
                <li>• Fabricated ("hallucinated") or nonsensical recommendations</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>
                  You must verify AI recommendations through professional inspection and assessment
                  before acting on them.
                </strong>{" "}
                The AI provides decision-support only; it does not make decisions for you. If you
                believe an AI output is incorrect, you can request a human review at
                support@refurbgenius.co.uk. See our{" "}
                <a href="/privacy" className="text-primary hover:underline">
                  Privacy Policy
                </a>{" "}
                for how AI processing and automated decision-making are handled.
              </p>

              <h3 className="mt-5 text-lg font-medium">Third-Party AI Providers</h3>
              <p className="mt-2 text-sm leading-relaxed">
                AI analysis is powered by OpenAI APIs. Their processing is subject to OpenAI's own
                terms and privacy policy. We do not opt in to model training using your content.
              </p>
            </section>

            {/* User Responsibilities */}
            <section>
              <h2 className="text-2xl font-semibold">6. Your Responsibilities</h2>

              <h3 className="mt-5 text-lg font-medium">Eligibility</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You must be at least 18 years old and able to enter into a binding contract to use
                the Platform.
              </p>

              <h3 className="mt-5 text-lg font-medium">Verification of Information</h3>
              <p className="mt-2 text-sm leading-relaxed">You are solely responsible for:</p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Verifying all property information you input is accurate and current</li>
                <li>• Confirming estimates with professional contractors</li>
                <li>
                  • Conducting legal due diligence (title checks, planning, environmental surveys)
                </li>
                <li>• Validating AI recommendations through qualified professionals</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Acceptable Use</h3>
              <p className="mt-2 text-sm leading-relaxed">You agree not to:</p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>
                  • Use the Platform for any unlawful purpose or in violation of applicable laws
                </li>
                <li>• Upload malicious files, viruses, or harmful content</li>
                <li>• Attempt to gain unauthorised access to the Platform or other users' data</li>
                <li>• Use the Platform to harass, threaten, or abuse others</li>
                <li>• Reverse engineer, decompile, or attempt to derive source code</li>
                <li>• Scrape data or use automated tools to extract information at scale</li>
                <li>
                  • Bypass security measures or carry out penetration testing without our written
                  authorisation
                </li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Content Responsibility</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You are responsible for all content you upload (photos, property descriptions,
                financial data). You warrant that:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• You have the right to upload and share this content</li>
                <li>
                  • Content does not infringe third-party intellectual property or privacy rights
                </li>
                <li>
                  • Content does not contain special category data or identifiable information of
                  third parties without a lawful basis
                </li>
              </ul>
            </section>

            {/* Intellectual Property */}
            <section>
              <h2 className="text-2xl font-semibold">7. Intellectual Property</h2>
              <p className="mt-3 text-sm leading-relaxed">
                The Platform, including its software, design, and branding, is owned by us or our
                licensors and is protected by intellectual property laws. You retain ownership of
                the content you upload. By uploading content, you grant us a limited licence to
                process and store it solely to provide the service to you. We do not claim ownership
                of your data and do not use it to train AI models.
              </p>
            </section>

            {/* Account Termination */}
            <section>
              <h2 className="text-2xl font-semibold">8. Account Termination</h2>

              <h3 className="mt-5 text-lg font-medium">Your Right to Delete</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You may delete your account at any time through your Settings. Upon deletion:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Your account and associated data will be marked for deletion</li>
                <li>• You will lose access to all projects and analyses</li>
                <li>• Deletion is processed within 30 days</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Our Right to Suspend or Terminate</h3>
              <p className="mt-2 text-sm leading-relaxed">
                We may suspend or terminate your access if you:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Materially breach these Terms</li>
                <li>• Engage in abusive, fraudulent, or malicious behaviour</li>
                <li>• Attempt unauthorised access or attacks</li>
              </ul>
              <p className="mt-3 text-sm leading-relaxed">
                Where it is reasonable to do so, we will give you notice and an opportunity to put
                things right. If we discontinue the Platform, we will give you at least 30 days'
                notice and a reasonable opportunity to export your data, except where we are
                prevented from doing so by law.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="text-2xl font-semibold">9. Liability</h2>

              <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="text-sm text-red-900 font-semibold">
                  Nothing in these Terms limits liability that cannot be limited by law.
                </p>
              </div>

              <p className="mt-3 text-sm leading-relaxed">
                Nothing in these Terms excludes or limits our liability for: (a) death or personal
                injury caused by our negligence; (b) fraud or fraudulent misrepresentation; (c) any
                breach of the rights you have under the Consumer Rights Act 2015 (where you are a
                consumer); or (d) any other liability that cannot be excluded or limited under the
                laws of England and Wales.
              </p>

              <p className="mt-3 text-sm leading-relaxed">
                Subject to the paragraph above, and to the fullest extent permitted by law, we are
                not liable for:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Investment losses, missed profits, or opportunity costs</li>
                <li>• Decisions you make in reliance on estimates or AI-generated content</li>
                <li>
                  • Loss or corruption of data, except where caused by our failure to take
                  reasonable care
                </li>
                <li>• Service interruptions outside our reasonable control</li>
                <li>• The acts or omissions of third-party processors (e.g. OpenAI, Supabase)</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>If you are a business user,</strong> we exclude all implied warranties to
                the extent permitted by law, and our total aggregate liability arising out of or in
                connection with the Platform is limited to the greater of (i) the total amount you
                paid us in the 12 months before the claim, or (ii) £100.
              </p>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>If you are a consumer,</strong> we are responsible for loss or damage you
                suffer that is a foreseeable result of our breach of these Terms or our failure to
                use reasonable care and skill, but we are not responsible for any loss or damage
                that is not foreseeable. This does not affect your statutory rights.
              </p>
            </section>

            {/* Disclaimer of Warranties */}
            <section>
              <h2 className="text-2xl font-semibold">10. Service Availability</h2>
              <p className="mt-3 text-sm leading-relaxed">
                We provide the Platform with reasonable care and skill, but we do not warrant that
                it will be uninterrupted, error-free, or that results will meet your specific
                requirements. Where you are a business user, the Platform is otherwise provided "as
                available" and we exclude implied warranties to the extent permitted by law. Where
                you are a consumer, your statutory rights are not affected by this section.
              </p>
            </section>

            {/* Indemnification */}
            <section>
              <h2 className="text-2xl font-semibold">11. Indemnification (Business Users)</h2>
              <p className="mt-3 text-sm leading-relaxed">
                If you use the Platform as a business user, you agree to indemnify and hold harmless
                Rissolol Ltd, its officers, and service providers from any third-party claims,
                damages, or reasonable costs arising from: your breach of these Terms, content you
                upload that infringes third-party rights, or your unlawful use of the Platform. This
                section does not apply to consumers.
              </p>
            </section>

            {/* Governing Law */}
            <section>
              <h2 className="text-2xl font-semibold">12. Governing Law & Jurisdiction</h2>
              <p className="mt-3 text-sm leading-relaxed">
                These Terms are governed by the laws of England and Wales. If you are a business
                user, the courts of England and Wales have exclusive jurisdiction. If you are a
                consumer, you may bring proceedings in the courts of the part of the United Kingdom
                in which you live, and you benefit from any mandatory consumer protections of that
                jurisdiction.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-2xl font-semibold">13. Contact & Questions</h2>
              <p className="mt-3 text-sm leading-relaxed">
                If you have questions about these Terms, please contact:
              </p>
              <div className="mt-3 rounded-lg bg-muted p-4">
                <p className="text-sm font-medium">Email: support@refurbgenius.co.uk</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Please include "Terms Question" in the subject line.
                </p>
              </div>
            </section>
          </div>

          {/* Footer Navigation */}
          <div className="mt-12 border-t border-border pt-8">
            <p className="text-sm text-muted-foreground">
              Related:{" "}
              <a href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </a>{" "}
              •{" "}
              <a href="/support" className="text-primary hover:underline">
                Support & Contact
              </a>
            </p>
          </div>
        </div>
      </div>
      <Toaster />
    </div>
  );
}
