import { createFileRoute } from "@tanstack/react-router";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/Navbar";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      {
        name: "description",
        content: "Terms of service for Refurb Genius — Please read before using our platform.",
      },
      {
        property: "og:title",
        content: "Terms of Service — Refurb Genius",
      },
    ],
  }),
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="py-8 px-4 sm:px-6 md:px-8">
        <div className="mx-auto max-w-4xl">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: May 2026</p>
          </div>

          {/* Beta Notice */}
          <div className="mb-8 rounded-lg border border-yellow-200 bg-yellow-50 p-4">
            <p className="text-sm font-semibold text-yellow-900">⚠️ Controlled-Beta Notice</p>
            <p className="mt-2 text-sm text-yellow-800">
              Refurb Genius is in controlled-beta testing. By using this service, you acknowledge
              that the platform is under active development, features may change rapidly, and
              service interruptions may occur without notice. Please review these terms carefully.
            </p>
          </div>

          {/* Content */}
          <div className="space-y-8 text-foreground">
            {/* Acceptance of Terms */}
            <section>
              <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
              <p className="mt-3 text-sm leading-relaxed">
                By accessing and using Refurb Genius ("the Platform"), you agree to be bound by
                these Terms of Service ("Terms"). If you do not agree to these Terms, you may not
                use the Platform. We reserve the right to modify these Terms at any time. Your
                continued use of the Platform following any changes constitutes your acceptance of
                the new Terms.
              </p>
            </section>

            {/* Controlled-Beta Status */}
            <section>
              <h2 className="text-2xl font-semibold">2. Controlled-Beta Status & Disclaimer</h2>

              <h3 className="mt-5 text-lg font-medium">Beta Service Disclaimer</h3>
              <p className="mt-2 text-sm leading-relaxed">
                Refurb Genius is provided on an "AS-IS" and "AS-AVAILABLE" basis during the
                controlled-beta phase. We make no representations or warranties regarding:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• The accuracy, completeness, or reliability of analysis results</li>
                <li>• Uninterrupted availability of the service</li>
                <li>• Absence of errors, bugs, or vulnerabilities</li>
                <li>• Persistence or safety of your data</li>
                <li>• Future compatibility or support for stored data</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Service Changes</h3>
              <p className="mt-2 text-sm leading-relaxed">During beta, we may:</p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Modify, suspend, or discontinue features without notice</li>
                <li>• Change data schemas or reset beta data</li>
                <li>• Introduce breaking changes to workflows</li>
                <li>• End the beta program and transition to paid service</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">No Guarantee of Continuation</h3>
              <p className="mt-2 text-sm leading-relaxed">
                We do not guarantee that the Platform will continue to operate beyond the
                controlled-beta phase. Participation in the beta program does not entitle you to
                access during general availability or production phases.
              </p>
            </section>

            {/* No Financial Advice */}
            <section>
              <h2 className="text-2xl font-semibold">3. No Financial Advice</h2>
              <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="text-sm text-red-900 font-semibold">
                  IMPORTANT: Refurb Genius does NOT provide financial advice.
                </p>
              </div>

              <p className="mt-3 text-sm leading-relaxed">
                All estimates, projections, and recommendations generated by Refurb Genius,
                including ROI calculations, yield estimates, profit forecasts, and investment
                scores, are:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Approximate and based on simplified models</li>
                <li>• For informational and planning purposes only</li>
                <li>• Not guarantees of actual financial outcomes</li>
                <li>• Not a substitute for professional financial, legal, or accounting advice</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>You must:</strong>
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Verify all estimates independently with qualified professionals</li>
                <li>• Conduct due diligence on all properties before investment</li>
                <li>• Consult a qualified financial advisor before making investment decisions</li>
                <li>
                  • Account for market conditions, tax implications, and personal circumstances
                </li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>We are not responsible for:</strong>
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Investment losses or missed opportunities</li>
                <li>• Inaccurate market estimates or regional assumptions</li>
                <li>• Changes in property values, rental markets, or economic conditions</li>
                <li>• Regulatory changes or tax implications you did not anticipate</li>
              </ul>
            </section>

            {/* Estimates & Projections */}
            <section>
              <h2 className="text-2xl font-semibold">4. Refurbishment Estimates & Projections</h2>

              <h3 className="mt-5 text-lg font-medium">Estimates Are Approximate</h3>
              <p className="mt-2 text-sm leading-relaxed">
                Refurbishment cost estimates are generated using:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Regional cost multipliers based on historical data</li>
                <li>• Property condition assessments (which may contain errors)</li>
                <li>• Simplified finish-level assumptions</li>
                <li>• Industry-average material and labour costs</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>These estimates may differ significantly from actual quotes.</strong> Always
                obtain competitive quotes from licensed contractors before committing to a project.
              </p>

              <h3 className="mt-5 text-lg font-medium">ROI & Yield Disclaimers</h3>
              <p className="mt-2 text-sm leading-relaxed">
                ROI, yield, and profit projections do not account for:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Taxes, stamp duty, or transaction costs</li>
                <li>• Maintenance reserves or void periods</li>
                <li>• Interest rates or financing costs</li>
                <li>• Tenant demand or local rental market volatility</li>
                <li>• Regulatory changes (environmental, rental, planning)</li>
                <li>• Force majeure or unforeseen circumstances</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Use at Your Own Risk</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You acknowledge that you are using these estimates at your own risk. We strongly
                recommend conducting professional valuations, surveys, and financial analysis before
                making any investment decisions.
              </p>
            </section>

            {/* AI Output Advisory */}
            <section>
              <h2 className="text-2xl font-semibold">5. AI-Generated Content & Analysis</h2>

              <h3 className="mt-5 text-lg font-medium">Accuracy of AI Analysis</h3>
              <p className="mt-2 text-sm leading-relaxed">
                AI-generated analyses (photo interpretation, design suggestions, damage assessments)
                are generated by machine learning models and may contain:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Misidentifications or incorrect room categorizations</li>
                <li>• Overstated or understated damage severity</li>
                <li>• Irrelevant or impractical design suggestions</li>
                <li>• Hallucinations or nonsensical recommendations</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>
                  You must verify AI recommendations through professional inspection and assessment
                  before acting on them.
                </strong>
              </p>

              <h3 className="mt-5 text-lg font-medium">No Liability for AI Errors</h3>
              <p className="mt-2 text-sm leading-relaxed">
                We are not liable for errors, omissions, or inaccuracies in AI-generated content.
                The Platform is a tool to supplement (not replace) professional surveys and expert
                review.
              </p>

              <h3 className="mt-5 text-lg font-medium">Third-Party AI Providers</h3>
              <p className="mt-2 text-sm leading-relaxed">
                AI analysis is powered by OpenAI APIs. Refer to OpenAI's terms of service for
                information on how they process your data. We are not responsible for errors or
                limitations in third-party AI services.
              </p>
            </section>

            {/* User Responsibilities */}
            <section>
              <h2 className="text-2xl font-semibold">6. Your Responsibilities</h2>

              <h3 className="mt-5 text-lg font-medium">Verification of Information</h3>
              <p className="mt-2 text-sm leading-relaxed">You are solely responsible for:</p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Verifying all property information you input is accurate and current</li>
                <li>• Confirming estimates with professional contractors</li>
                <li>
                  • Conducting legal due diligence (title checks, planning, environmental surveys)
                </li>
                <li>• Validating AI recommendations through licensed professionals</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Acceptable Use</h3>
              <p className="mt-2 text-sm leading-relaxed">You agree not to:</p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>
                  • Use the Platform for any unlawful purpose or in violation of applicable laws
                </li>
                <li>• Upload malicious files, viruses, or harmful content</li>
                <li>• Attempt to gain unauthorized access to the Platform or other users' data</li>
                <li>• Use the Platform to harass, threaten, or abuse others</li>
                <li>• Reverse engineer, decompile, or attempt to derive source code</li>
                <li>• Scrape data or use automated tools to extract information at scale</li>
                <li>
                  • Bypass security measures or engage in penetration testing without authorization
                </li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Content Responsibility</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You are responsible for all content you upload (photos, property descriptions,
                financial data). You warrant that:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• You have the right to upload and share this content</li>
                <li>
                  • Content does not infringe third-party intellectual property or privacy rights
                </li>
                <li>
                  • Content does not contain personally identifiable information of third parties
                </li>
              </ul>
            </section>

            {/* Account Termination */}
            <section>
              <h2 className="text-2xl font-semibold">7. Account Termination</h2>

              <h3 className="mt-5 text-lg font-medium">Your Right to Delete</h3>
              <p className="mt-2 text-sm leading-relaxed">
                You may delete your account at any time through your Settings. Upon deletion:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Your account and associated data will be marked for deletion</li>
                <li>• You will lose access to all projects and analyses</li>
                <li>• Deletion is processed within 7 business days</li>
              </ul>

              <h3 className="mt-5 text-lg font-medium">Our Right to Terminate</h3>
              <p className="mt-2 text-sm leading-relaxed">
                We may terminate your account or suspend access if you:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Violate these Terms</li>
                <li>• Engage in abusive or malicious behavior</li>
                <li>• Attempt unauthorized access or attacks</li>
                <li>• End the controlled-beta program or transition to paid service</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                Upon termination by us, you will have 30 days to export or retrieve your data before
                permanent deletion.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="text-2xl font-semibold">8. Limitation of Liability</h2>

              <div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="text-sm text-red-900 font-semibold">
                  TO THE FULLEST EXTENT PERMITTED BY LAW:
                </p>
              </div>

              <p className="mt-3 text-sm leading-relaxed">
                Refurb Genius and its owners, operators, and contributors are not liable for:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Any direct, indirect, incidental, or consequential damages</li>
                <li>• Investment losses, missed profits, or opportunity costs</li>
                <li>• Data loss, corruption, or unauthorized access</li>
                <li>• Service interruptions or unavailability</li>
                <li>• Third-party processor actions (OpenAI, Supabase, etc.)</li>
                <li>• Errors in estimates, projections, or AI-generated content</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                <strong>
                  Your total liability to us is limited to the amount you have paid for the Platform
                  (if any).
                </strong>{" "}
                If you have not paid, your liability is £0.
              </p>

              <p className="mt-3 text-sm leading-relaxed">
                Some jurisdictions do not allow limitations of liability, so this provision may not
                apply to you in full.
              </p>
            </section>

            {/* Disclaimer of Warranties */}
            <section>
              <h2 className="text-2xl font-semibold">9. Disclaimer of Warranties</h2>

              <p className="mt-3 text-sm leading-relaxed">
                The Platform is provided "AS-IS" without any warranties, express or implied,
                including:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Warranties of merchantability or fitness for a particular purpose</li>
                <li>• Warranties of non-infringement or title</li>
                <li>• Warranties of accuracy, completeness, or reliability</li>
              </ul>

              <p className="mt-3 text-sm leading-relaxed">
                We do not warrant that the Platform will meet your specific needs, operate without
                errors, or be available uninterrupted.
              </p>
            </section>

            {/* Indemnification */}
            <section>
              <h2 className="text-2xl font-semibold">10. Indemnification</h2>
              <p className="mt-3 text-sm leading-relaxed">
                You agree to indemnify and hold harmless Refurb Genius, its owners, operators,
                contributors, and service providers from any claims, damages, or costs arising from:
              </p>
              <ul className="mt-2 space-y-1 text-sm leading-relaxed">
                <li>• Your use of the Platform or violation of these Terms</li>
                <li>• Your investment decisions or reliance on Platform outputs</li>
                <li>• Content you upload or share</li>
                <li>• Infringement of third-party rights by your content</li>
              </ul>
            </section>

            {/* Governing Law */}
            <section>
              <h2 className="text-2xl font-semibold">11. Governing Law & Jurisdiction</h2>
              <p className="mt-3 text-sm leading-relaxed">
                These Terms are governed by and construed in accordance with the laws of England and
                Wales. Any legal action or proceeding relating to these Terms shall be subject to
                the exclusive jurisdiction of the courts of England and Wales.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-2xl font-semibold">12. Contact & Questions</h2>
              <p className="mt-3 text-sm leading-relaxed">
                If you have questions about these Terms, please contact:
              </p>
              <div className="mt-3 rounded-lg bg-muted p-4">
                <p className="text-sm font-medium">Email: support@refurbgenius.co.uk</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Please include "Terms Question" in the subject line.
                </p>
              </div>
            </section>
          </div>

          {/* Footer Navigation */}
          <div className="mt-12 border-t border-border pt-8">
            <p className="text-sm text-muted-foreground">
              Related:{" "}
              <a href="/privacy" className="text-primary hover:underline">
                Privacy Policy
              </a>{" "}
              •{" "}
              <a href="/support" className="text-primary hover:underline">
                Support & Contact
              </a>
            </p>
          </div>
        </div>
      </div>
      <Toaster />
    </div>
  );
}
