/**
 * Projects feature — public API.
 *
 * Presentation consumers import stage mutation, IA-1 workflow shell, and IA-2
 * next-action resolver from here.
 * Infrastructure is intentionally not re-exported.
 * List/detail/create remain on transitional @/hooks/useProjects (out of AO-1M4).
 * Broad UI consumer migration of continuation (Dashboard/Overview) is IA-6.
 */
export {
  useSetProjectStage,
  type SetProjectStageVariables,
} from "./presentation/hooks/useSetProjectStage";

export {
  useProjectFiveStageWorkflow,
  type ProjectFiveStageWorkflowResult,
} from "./presentation/hooks/useProjectFiveStageWorkflow";

export {
  ProjectWorkflowShell,
  ProjectStageNav,
  ProjectContinuationCard,
  NewProjectEntry,
  type ProjectWorkflowShellProject,
  type ProjectContinuationCardProps,
  useProjectWorkflowOperationFlags,
  beginProjectWorkflowOperation,
  endProjectWorkflowOperation,
  getProjectWorkflowOperationFlags,
  resetProjectWorkflowOperationRegistryForTests,
  setProjectWorkflowOperationRunning,
  subscribeProjectWorkflowOperations,
  withProjectWorkflowOperationRunning,
  type ProjectWorkflowOperationFlags,
  type ProjectWorkflowOperationStage,
} from "./presentation";

export {
  PROJECT_OVERVIEW_IS_WORKFLOW_STAGE,
  PROJECT_WORKFLOW_STAGE_IDS,
  PROJECT_WORKFLOW_STAGES,
  PROJECT_WORKFLOW_STATUS_LABELS,
  PROJECT_NEXT_ACTION_KINDS,
  PROJECT_NEXT_ACTION_LABELS,
  PROJECT_NEXT_ACTION_REASONS,
  PROJECT_STAGE_PROGRESS_LABELS,
  buildProjectIdentitySubtitle,
  buildProjectIdentityTitle,
  analysisCurrencyFromEvidence,
  analysisShellFlagsFromCurrency,
  buildPhotosAnalysisWorkflowState,
  redesignCurrencyFromEvidence,
  redesignShellFlagsFromCurrency,
  scopeCurrencyFromEvidence,
  scopeShellFlagsFromCurrency,
  estimateCurrencyFromEvidence,
  estimateShellFlagsFromCurrency,
  exportCurrencyFromEvidence,
  exportShellFlagsFromCurrency,
  composeProjectWorkflowState,
  buildProjectNextActionRoute,
  buildProjectWorkflowStages,
  explainProjectNextActionReason,
  workflowAllStagesComplete,
  workflowHasNeedsAttention,
  isCanonicalWorkflowStatus,
  isProjectNextActionKind,
  photosCurrencyFromEvidence,
  progressFromProjectFlags,
  resolveActiveWorkflowStage,
  resolveProjectNextAction,
  resolveStageStatus,
  stageDestination,
  type AnalysisAuthorityEvidence,
  type AnalysisWorkflowState,
  type DurablePhotoIdentity,
  type PhotosAnalysisAdapterInput,
  type EstimateWorkflowState,
  type ExportWorkflowState,
  type PhotosWorkflowState,
  type ProjectNextAction,
  type ProjectNextActionKind,
  type ProjectNextActionReason,
  type ProjectWorkflowDestination,
  type ProjectWorkflowEntitlements,
  type ProjectWorkflowProgressInput,
  type ProjectWorkflowRouteContext,
  type ProjectWorkflowRouteTo,
  type ProjectWorkflowStageDefinition,
  type ProjectWorkflowStageId,
  type ProjectWorkflowStagePresentation,
  type ProjectWorkflowState,
  type ProjectWorkflowStatusLabel,
  type RedesignWorkflowState,
  type ResolveProjectNextActionInput,
  type ScopeWorkflowState,
  type ScopeAuthorityEvidence,
  type EstimateAuthorityEvidence,
  type ExportSnapshotEvidence,
  type ComposeProjectWorkflowStateInput,
  type WorkflowAuthorityCurrency,
  MONEY_NOT_SET_LABEL,
  formatMoneyPresence,
  projectOptionalMoneyForDisplay,
} from "./domain";
