export {
  ROOM_TYPES,
  CONDITION_LEVELS,
  REFURB_LEVELS,
  type RoomType,
  type ConditionLevel,
  type RefurbLevel,
  type AnalysisSource,
  type RoomAnalysis,
  type AnalysisPhotoSource,
} from "./types";
export { buildMockRoomAnalyses } from "./mockData";
export {
  isImageFile,
  imageContentType,
  isSuccessfulAnalysis,
  hasFallbackResults,
  isActionableAnalysisSet,
  averageConfidence,
  CONFIDENCE_REVIEW_THRESHOLD,
  needsHumanReview,
  isRetryableAnalysis,
  countNeedingReview,
  analysisPhotoKey,
  mergeAnalysesRetainingGood,
  photoAiStatus,
  groupAnalysesByRoom,
  findDuplicatePhotoIds,
  suggestWithoutOverwrite,
  hasMockAnalysis,
  isMockOnlyAnalysisSet,
  isStaleAnalysisRelativeToCatalogue,
  isProductionValidAnalysisSet,
  preferAnalysesForCurrentCatalogue,
  durablePhotoCatalogueIdentity,
  catalogueIdentityFingerprint,
  assertAnalysisProvenance,
  PHOTO_ANALYSIS_NO_SOURCE_PHOTOS,
  PHOTO_ANALYSIS_CARDINALITY_MISMATCH,
  PHOTO_ANALYSIS_PROVENANCE_MISMATCH,
  PHOTO_ANALYSIS_MOCK_FORBIDDEN,
  PHOTO_ANALYSIS_STALE_REQUIRES_REANALYSIS,
  PHOTO_ANALYSIS_PROJECT_NOT_AUTHORISED,
  PHOTO_ANALYSIS_SOURCE_NOT_AUTHORISED,
  PHOTO_ANALYSIS_SOURCE_SET_MISMATCH,
  PHOTO_ANALYSIS_PERSISTENCE_FAILED,
  PhotoAnalysisError,
  noSourcePhotosError,
  staleAnalysisRequiresReanalysisError,
  projectNotAuthorisedError,
  sourceNotAuthorisedError,
  sourceSetMismatchError,
  persistenceFailedError,
  type PhotoAiStatus,
  type RoomAnalysisGroup,
} from "./rules";
export {
  roomTypeSchema,
  conditionLevelSchema,
  refurbLevelSchema,
  analysisSourceSchema,
  roomAnalysisSchema,
  safeParseRoomAnalysis,
  type ValidatedRoomAnalysisInput,
} from "./validation";
export {
  parsePhotoAnalysisContent,
  serializePhotoAnalysisContent,
  mapPhotoAnalysisRow,
  createPhotoAnalysisAppModel,
  EMPTY_PHOTO_ANALYSIS_CONTENT,
  type PhotoAnalysisAppModel,
  type PhotoAnalysisContent,
  type PhotoAnalysisDefect,
  type PhotoAnalysisMaterial,
  type PhotoAnalysisCostSuggestions,
  type PhotoAnalysisDbRowLike,
  type PhotoAnalysisJson,
} from "./photo-analysis-content";
