/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealCopilotIndexRouteImport } from './routes/deal-copilot/index'
import { Route as TradesProfileRouteImport } from './routes/trades.profile'
import { Route as TradesNewRouteImport } from './routes/trades.new'
import { Route as TradesJobIdRouteImport } from './routes/trades.$jobId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as DealCopilotNewRouteImport } from './routes/deal-copilot/new'
import { Route as DealCopilotOpportunityIdRouteImport } from './routes/deal-copilot/$opportunityId'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as TradesJobIdEditRouteImport } from './routes/trades.$jobId.edit'
import { Route as ProjectsIdUploadRouteImport } from './routes/projects.$id.upload'
import { Route as ProjectsIdReportRouteImport } from './routes/projects.$id.report'
import { Route as ProjectsIdEstimateRouteImport } from './routes/projects.$id.estimate'
import { Route as ProjectsIdAnalysisRouteImport } from './routes/projects.$id.analysis'
import { Route as DealCopilotOpportunityIdEditRouteImport } from './routes/deal-copilot/$opportunityId.edit'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealCopilotIndexRoute = DealCopilotIndexRouteImport.update({
  id: '/deal-copilot/',
  path: '/deal-copilot/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesProfileRoute = TradesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TradesRoute,
} as any)
const TradesNewRoute = TradesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TradesRoute,
} as any)
const TradesJobIdRoute = TradesJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => TradesRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealCopilotNewRoute = DealCopilotNewRouteImport.update({
  id: '/deal-copilot/new',
  path: '/deal-copilot/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealCopilotOpportunityIdRoute =
  DealCopilotOpportunityIdRouteImport.update({
    id: '/deal-copilot/$opportunityId',
    path: '/deal-copilot/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesJobIdEditRoute = TradesJobIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TradesJobIdRoute,
} as any)
const ProjectsIdUploadRoute = ProjectsIdUploadRouteImport.update({
  id: '/projects/$id/upload',
  path: '/projects/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdReportRoute = ProjectsIdReportRouteImport.update({
  id: '/projects/$id/report',
  path: '/projects/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEstimateRoute = ProjectsIdEstimateRouteImport.update({
  id: '/projects/$id/estimate',
  path: '/projects/$id/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdAnalysisRoute = ProjectsIdAnalysisRouteImport.update({
  id: '/projects/$id/analysis',
  path: '/projects/$id/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DealCopilotOpportunityIdEditRoute =
  DealCopilotOpportunityIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DealCopilotOpportunityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRouteWithChildren
  '/deal-copilot/$opportunityId': typeof DealCopilotOpportunityIdRouteWithChildren
  '/deal-copilot/new': typeof DealCopilotNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/trades/$jobId': typeof TradesJobIdRouteWithChildren
  '/trades/new': typeof TradesNewRoute
  '/trades/profile': typeof TradesProfileRoute
  '/deal-copilot/': typeof DealCopilotIndexRoute
  '/deal-copilot/$opportunityId/edit': typeof DealCopilotOpportunityIdEditRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/estimate': typeof ProjectsIdEstimateRoute
  '/projects/$id/report': typeof ProjectsIdReportRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
  '/trades/$jobId/edit': typeof TradesJobIdEditRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRouteWithChildren
  '/deal-copilot/$opportunityId': typeof DealCopilotOpportunityIdRouteWithChildren
  '/deal-copilot/new': typeof DealCopilotNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/trades/$jobId': typeof TradesJobIdRouteWithChildren
  '/trades/new': typeof TradesNewRoute
  '/trades/profile': typeof TradesProfileRoute
  '/deal-copilot': typeof DealCopilotIndexRoute
  '/deal-copilot/$opportunityId/edit': typeof DealCopilotOpportunityIdEditRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/estimate': typeof ProjectsIdEstimateRoute
  '/projects/$id/report': typeof ProjectsIdReportRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
  '/trades/$jobId/edit': typeof TradesJobIdEditRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRouteWithChildren
  '/deal-copilot/$opportunityId': typeof DealCopilotOpportunityIdRouteWithChildren
  '/deal-copilot/new': typeof DealCopilotNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/trades/$jobId': typeof TradesJobIdRouteWithChildren
  '/trades/new': typeof TradesNewRoute
  '/trades/profile': typeof TradesProfileRoute
  '/deal-copilot/': typeof DealCopilotIndexRoute
  '/deal-copilot/$opportunityId/edit': typeof DealCopilotOpportunityIdEditRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/estimate': typeof ProjectsIdEstimateRoute
  '/projects/$id/report': typeof ProjectsIdReportRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
  '/trades/$jobId/edit': typeof TradesJobIdEditRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/trades'
    | '/deal-copilot/$opportunityId'
    | '/deal-copilot/new'
    | '/projects/new'
    | '/trades/$jobId'
    | '/trades/new'
    | '/trades/profile'
    | '/deal-copilot/'
    | '/deal-copilot/$opportunityId/edit'
    | '/projects/$id/analysis'
    | '/projects/$id/estimate'
    | '/projects/$id/report'
    | '/projects/$id/upload'
    | '/trades/$jobId/edit'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/trades'
    | '/deal-copilot/$opportunityId'
    | '/deal-copilot/new'
    | '/projects/new'
    | '/trades/$jobId'
    | '/trades/new'
    | '/trades/profile'
    | '/deal-copilot'
    | '/deal-copilot/$opportunityId/edit'
    | '/projects/$id/analysis'
    | '/projects/$id/estimate'
    | '/projects/$id/report'
    | '/projects/$id/upload'
    | '/trades/$jobId/edit'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/trades'
    | '/deal-copilot/$opportunityId'
    | '/deal-copilot/new'
    | '/projects/new'
    | '/trades/$jobId'
    | '/trades/new'
    | '/trades/profile'
    | '/deal-copilot/'
    | '/deal-copilot/$opportunityId/edit'
    | '/projects/$id/analysis'
    | '/projects/$id/estimate'
    | '/projects/$id/report'
    | '/projects/$id/upload'
    | '/trades/$jobId/edit'
    | '/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRouteWithChildren
  DealCopilotOpportunityIdRoute: typeof DealCopilotOpportunityIdRouteWithChildren
  DealCopilotNewRoute: typeof DealCopilotNewRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  DealCopilotIndexRoute: typeof DealCopilotIndexRoute
  ProjectsIdAnalysisRoute: typeof ProjectsIdAnalysisRoute
  ProjectsIdEstimateRoute: typeof ProjectsIdEstimateRoute
  ProjectsIdReportRoute: typeof ProjectsIdReportRoute
  ProjectsIdUploadRoute: typeof ProjectsIdUploadRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-copilot/': {
      id: '/deal-copilot/'
      path: '/deal-copilot'
      fullPath: '/deal-copilot/'
      preLoaderRoute: typeof DealCopilotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/profile': {
      id: '/trades/profile'
      path: '/profile'
      fullPath: '/trades/profile'
      preLoaderRoute: typeof TradesProfileRouteImport
      parentRoute: typeof TradesRoute
    }
    '/trades/new': {
      id: '/trades/new'
      path: '/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof TradesNewRouteImport
      parentRoute: typeof TradesRoute
    }
    '/trades/$jobId': {
      id: '/trades/$jobId'
      path: '/$jobId'
      fullPath: '/trades/$jobId'
      preLoaderRoute: typeof TradesJobIdRouteImport
      parentRoute: typeof TradesRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-copilot/new': {
      id: '/deal-copilot/new'
      path: '/deal-copilot/new'
      fullPath: '/deal-copilot/new'
      preLoaderRoute: typeof DealCopilotNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-copilot/$opportunityId': {
      id: '/deal-copilot/$opportunityId'
      path: '/deal-copilot/$opportunityId'
      fullPath: '/deal-copilot/$opportunityId'
      preLoaderRoute: typeof DealCopilotOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$jobId/edit': {
      id: '/trades/$jobId/edit'
      path: '/edit'
      fullPath: '/trades/$jobId/edit'
      preLoaderRoute: typeof TradesJobIdEditRouteImport
      parentRoute: typeof TradesJobIdRoute
    }
    '/projects/$id/upload': {
      id: '/projects/$id/upload'
      path: '/projects/$id/upload'
      fullPath: '/projects/$id/upload'
      preLoaderRoute: typeof ProjectsIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/report': {
      id: '/projects/$id/report'
      path: '/projects/$id/report'
      fullPath: '/projects/$id/report'
      preLoaderRoute: typeof ProjectsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/estimate': {
      id: '/projects/$id/estimate'
      path: '/projects/$id/estimate'
      fullPath: '/projects/$id/estimate'
      preLoaderRoute: typeof ProjectsIdEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/analysis': {
      id: '/projects/$id/analysis'
      path: '/projects/$id/analysis'
      fullPath: '/projects/$id/analysis'
      preLoaderRoute: typeof ProjectsIdAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-copilot/$opportunityId/edit': {
      id: '/deal-copilot/$opportunityId/edit'
      path: '/edit'
      fullPath: '/deal-copilot/$opportunityId/edit'
      preLoaderRoute: typeof DealCopilotOpportunityIdEditRouteImport
      parentRoute: typeof DealCopilotOpportunityIdRoute
    }
  }
}

interface TradesJobIdRouteChildren {
  TradesJobIdEditRoute: typeof TradesJobIdEditRoute
}

const TradesJobIdRouteChildren: TradesJobIdRouteChildren = {
  TradesJobIdEditRoute: TradesJobIdEditRoute,
}

const TradesJobIdRouteWithChildren = TradesJobIdRoute._addFileChildren(
  TradesJobIdRouteChildren,
)

interface TradesRouteChildren {
  TradesJobIdRoute: typeof TradesJobIdRouteWithChildren
  TradesNewRoute: typeof TradesNewRoute
  TradesProfileRoute: typeof TradesProfileRoute
}

const TradesRouteChildren: TradesRouteChildren = {
  TradesJobIdRoute: TradesJobIdRouteWithChildren,
  TradesNewRoute: TradesNewRoute,
  TradesProfileRoute: TradesProfileRoute,
}

const TradesRouteWithChildren =
  TradesRoute._addFileChildren(TradesRouteChildren)

interface DealCopilotOpportunityIdRouteChildren {
  DealCopilotOpportunityIdEditRoute: typeof DealCopilotOpportunityIdEditRoute
}

const DealCopilotOpportunityIdRouteChildren: DealCopilotOpportunityIdRouteChildren =
  {
    DealCopilotOpportunityIdEditRoute: DealCopilotOpportunityIdEditRoute,
  }

const DealCopilotOpportunityIdRouteWithChildren =
  DealCopilotOpportunityIdRoute._addFileChildren(
    DealCopilotOpportunityIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRouteWithChildren,
  DealCopilotOpportunityIdRoute: DealCopilotOpportunityIdRouteWithChildren,
  DealCopilotNewRoute: DealCopilotNewRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  DealCopilotIndexRoute: DealCopilotIndexRoute,
  ProjectsIdAnalysisRoute: ProjectsIdAnalysisRoute,
  ProjectsIdEstimateRoute: ProjectsIdEstimateRoute,
  ProjectsIdReportRoute: ProjectsIdReportRoute,
  ProjectsIdUploadRoute: ProjectsIdUploadRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
