/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradesJobIdRouteImport } from './routes/trades_.$jobId'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMarketplaceRouteImport } from './routes/_authed/marketplace'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDealCopilotIndexRouteImport } from './routes/_authed/deal-copilot/index'
import { Route as AuthedTradesProfileRouteImport } from './routes/_authed/trades_.profile'
import { Route as AuthedTradesNewRouteImport } from './routes/_authed/trades_.new'
import { Route as AuthedProjectsNewRouteImport } from './routes/_authed/projects.new'
import { Route as AuthedDealCopilotNewRouteImport } from './routes/_authed/deal-copilot/new'
import { Route as AuthedDealCopilotOpportunityIdRouteImport } from './routes/_authed/deal-copilot/$opportunityId'
import { Route as AuthedProjectsIdIndexRouteImport } from './routes/_authed/projects.$id.index'
import { Route as AuthedTradesJobIdEditRouteImport } from './routes/_authed/trades_.$jobId_.edit'
import { Route as AuthedProjectsIdUploadRouteImport } from './routes/_authed/projects.$id.upload'
import { Route as AuthedProjectsIdScopeRouteImport } from './routes/_authed/projects.$id.scope'
import { Route as AuthedProjectsIdReportRouteImport } from './routes/_authed/projects.$id.report'
import { Route as AuthedProjectsIdEstimateRouteImport } from './routes/_authed/projects.$id.estimate'
import { Route as AuthedProjectsIdAnalysisRouteImport } from './routes/_authed/projects.$id.analysis'
import { Route as AuthedDealCopilotOpportunityIdEditRouteImport } from './routes/_authed/deal-copilot/$opportunityId.edit'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesJobIdRoute = TradesJobIdRouteImport.update({
  id: '/trades_/$jobId',
  path: '/trades/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleryRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMarketplaceRoute = AuthedMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDealCopilotIndexRoute = AuthedDealCopilotIndexRouteImport.update({
  id: '/deal-copilot/',
  path: '/deal-copilot/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTradesProfileRoute = AuthedTradesProfileRouteImport.update({
  id: '/trades_/profile',
  path: '/trades/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTradesNewRoute = AuthedTradesNewRouteImport.update({
  id: '/trades_/new',
  path: '/trades/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsNewRoute = AuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDealCopilotNewRoute = AuthedDealCopilotNewRouteImport.update({
  id: '/deal-copilot/new',
  path: '/deal-copilot/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDealCopilotOpportunityIdRoute =
  AuthedDealCopilotOpportunityIdRouteImport.update({
    id: '/deal-copilot/$opportunityId',
    path: '/deal-copilot/$opportunityId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsIdIndexRoute = AuthedProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTradesJobIdEditRoute = AuthedTradesJobIdEditRouteImport.update({
  id: '/trades_/$jobId_/edit',
  path: '/trades/$jobId/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIdUploadRoute = AuthedProjectsIdUploadRouteImport.update({
  id: '/projects/$id/upload',
  path: '/projects/$id/upload',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIdScopeRoute = AuthedProjectsIdScopeRouteImport.update({
  id: '/projects/$id/scope',
  path: '/projects/$id/scope',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIdReportRoute = AuthedProjectsIdReportRouteImport.update({
  id: '/projects/$id/report',
  path: '/projects/$id/report',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIdEstimateRoute =
  AuthedProjectsIdEstimateRouteImport.update({
    id: '/projects/$id/estimate',
    path: '/projects/$id/estimate',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsIdAnalysisRoute =
  AuthedProjectsIdAnalysisRouteImport.update({
    id: '/projects/$id/analysis',
    path: '/projects/$id/analysis',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDealCopilotOpportunityIdEditRoute =
  AuthedDealCopilotOpportunityIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedDealCopilotOpportunityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trades': typeof TradesRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/marketplace': typeof AuthedMarketplaceRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/trades/$jobId': typeof TradesJobIdRoute
  '/deal-copilot/$opportunityId': typeof AuthedDealCopilotOpportunityIdRouteWithChildren
  '/deal-copilot/new': typeof AuthedDealCopilotNewRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/trades/new': typeof AuthedTradesNewRoute
  '/trades/profile': typeof AuthedTradesProfileRoute
  '/deal-copilot/': typeof AuthedDealCopilotIndexRoute
  '/deal-copilot/$opportunityId/edit': typeof AuthedDealCopilotOpportunityIdEditRoute
  '/projects/$id/analysis': typeof AuthedProjectsIdAnalysisRoute
  '/projects/$id/estimate': typeof AuthedProjectsIdEstimateRoute
  '/projects/$id/report': typeof AuthedProjectsIdReportRoute
  '/projects/$id/scope': typeof AuthedProjectsIdScopeRoute
  '/projects/$id/upload': typeof AuthedProjectsIdUploadRoute
  '/trades/$jobId/edit': typeof AuthedTradesJobIdEditRoute
  '/projects/$id/': typeof AuthedProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trades': typeof TradesRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/marketplace': typeof AuthedMarketplaceRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/trades/$jobId': typeof TradesJobIdRoute
  '/deal-copilot/$opportunityId': typeof AuthedDealCopilotOpportunityIdRouteWithChildren
  '/deal-copilot/new': typeof AuthedDealCopilotNewRoute
  '/projects/new': typeof AuthedProjectsNewRoute
  '/trades/new': typeof AuthedTradesNewRoute
  '/trades/profile': typeof AuthedTradesProfileRoute
  '/deal-copilot': typeof AuthedDealCopilotIndexRoute
  '/deal-copilot/$opportunityId/edit': typeof AuthedDealCopilotOpportunityIdEditRoute
  '/projects/$id/analysis': typeof AuthedProjectsIdAnalysisRoute
  '/projects/$id/estimate': typeof AuthedProjectsIdEstimateRoute
  '/projects/$id/report': typeof AuthedProjectsIdReportRoute
  '/projects/$id/scope': typeof AuthedProjectsIdScopeRoute
  '/projects/$id/upload': typeof AuthedProjectsIdUploadRoute
  '/trades/$jobId/edit': typeof AuthedTradesJobIdEditRoute
  '/projects/$id': typeof AuthedProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trades': typeof TradesRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/marketplace': typeof AuthedMarketplaceRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/trades_/$jobId': typeof TradesJobIdRoute
  '/_authed/deal-copilot/$opportunityId': typeof AuthedDealCopilotOpportunityIdRouteWithChildren
  '/_authed/deal-copilot/new': typeof AuthedDealCopilotNewRoute
  '/_authed/projects/new': typeof AuthedProjectsNewRoute
  '/_authed/trades_/new': typeof AuthedTradesNewRoute
  '/_authed/trades_/profile': typeof AuthedTradesProfileRoute
  '/_authed/deal-copilot/': typeof AuthedDealCopilotIndexRoute
  '/_authed/deal-copilot/$opportunityId/edit': typeof AuthedDealCopilotOpportunityIdEditRoute
  '/_authed/projects/$id/analysis': typeof AuthedProjectsIdAnalysisRoute
  '/_authed/projects/$id/estimate': typeof AuthedProjectsIdEstimateRoute
  '/_authed/projects/$id/report': typeof AuthedProjectsIdReportRoute
  '/_authed/projects/$id/scope': typeof AuthedProjectsIdScopeRoute
  '/_authed/projects/$id/upload': typeof AuthedProjectsIdUploadRoute
  '/_authed/trades_/$jobId_/edit': typeof AuthedTradesJobIdEditRoute
  '/_authed/projects/$id/': typeof AuthedProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gallery'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/trades'
    | '/admin'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/auth/callback'
    | '/gallery/$slug'
    | '/trades/$jobId'
    | '/deal-copilot/$opportunityId'
    | '/deal-copilot/new'
    | '/projects/new'
    | '/trades/new'
    | '/trades/profile'
    | '/deal-copilot/'
    | '/deal-copilot/$opportunityId/edit'
    | '/projects/$id/analysis'
    | '/projects/$id/estimate'
    | '/projects/$id/report'
    | '/projects/$id/scope'
    | '/projects/$id/upload'
    | '/trades/$jobId/edit'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gallery'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/trades'
    | '/admin'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/auth/callback'
    | '/gallery/$slug'
    | '/trades/$jobId'
    | '/deal-copilot/$opportunityId'
    | '/deal-copilot/new'
    | '/projects/new'
    | '/trades/new'
    | '/trades/profile'
    | '/deal-copilot'
    | '/deal-copilot/$opportunityId/edit'
    | '/projects/$id/analysis'
    | '/projects/$id/estimate'
    | '/projects/$id/report'
    | '/projects/$id/scope'
    | '/projects/$id/upload'
    | '/trades/$jobId/edit'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/gallery'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/trades'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/_authed/marketplace'
    | '/_authed/settings'
    | '/auth_/callback'
    | '/gallery/$slug'
    | '/trades_/$jobId'
    | '/_authed/deal-copilot/$opportunityId'
    | '/_authed/deal-copilot/new'
    | '/_authed/projects/new'
    | '/_authed/trades_/new'
    | '/_authed/trades_/profile'
    | '/_authed/deal-copilot/'
    | '/_authed/deal-copilot/$opportunityId/edit'
    | '/_authed/projects/$id/analysis'
    | '/_authed/projects/$id/estimate'
    | '/_authed/projects/$id/report'
    | '/_authed/projects/$id/scope'
    | '/_authed/projects/$id/upload'
    | '/_authed/trades_/$jobId_/edit'
    | '/_authed/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TradesRoute: typeof TradesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  TradesJobIdRoute: typeof TradesJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades_/$jobId': {
      id: '/trades_/$jobId'
      path: '/trades/$jobId'
      fullPath: '/trades/$jobId'
      preLoaderRoute: typeof TradesJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketplace': {
      id: '/_authed/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthedMarketplaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deal-copilot/': {
      id: '/_authed/deal-copilot/'
      path: '/deal-copilot'
      fullPath: '/deal-copilot/'
      preLoaderRoute: typeof AuthedDealCopilotIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trades_/profile': {
      id: '/_authed/trades_/profile'
      path: '/trades/profile'
      fullPath: '/trades/profile'
      preLoaderRoute: typeof AuthedTradesProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trades_/new': {
      id: '/_authed/trades_/new'
      path: '/trades/new'
      fullPath: '/trades/new'
      preLoaderRoute: typeof AuthedTradesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/new': {
      id: '/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthedProjectsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deal-copilot/new': {
      id: '/_authed/deal-copilot/new'
      path: '/deal-copilot/new'
      fullPath: '/deal-copilot/new'
      preLoaderRoute: typeof AuthedDealCopilotNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deal-copilot/$opportunityId': {
      id: '/_authed/deal-copilot/$opportunityId'
      path: '/deal-copilot/$opportunityId'
      fullPath: '/deal-copilot/$opportunityId'
      preLoaderRoute: typeof AuthedDealCopilotOpportunityIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/': {
      id: '/_authed/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthedProjectsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trades_/$jobId_/edit': {
      id: '/_authed/trades_/$jobId_/edit'
      path: '/trades/$jobId/edit'
      fullPath: '/trades/$jobId/edit'
      preLoaderRoute: typeof AuthedTradesJobIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/upload': {
      id: '/_authed/projects/$id/upload'
      path: '/projects/$id/upload'
      fullPath: '/projects/$id/upload'
      preLoaderRoute: typeof AuthedProjectsIdUploadRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/scope': {
      id: '/_authed/projects/$id/scope'
      path: '/projects/$id/scope'
      fullPath: '/projects/$id/scope'
      preLoaderRoute: typeof AuthedProjectsIdScopeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/report': {
      id: '/_authed/projects/$id/report'
      path: '/projects/$id/report'
      fullPath: '/projects/$id/report'
      preLoaderRoute: typeof AuthedProjectsIdReportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/estimate': {
      id: '/_authed/projects/$id/estimate'
      path: '/projects/$id/estimate'
      fullPath: '/projects/$id/estimate'
      preLoaderRoute: typeof AuthedProjectsIdEstimateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$id/analysis': {
      id: '/_authed/projects/$id/analysis'
      path: '/projects/$id/analysis'
      fullPath: '/projects/$id/analysis'
      preLoaderRoute: typeof AuthedProjectsIdAnalysisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deal-copilot/$opportunityId/edit': {
      id: '/_authed/deal-copilot/$opportunityId/edit'
      path: '/edit'
      fullPath: '/deal-copilot/$opportunityId/edit'
      preLoaderRoute: typeof AuthedDealCopilotOpportunityIdEditRouteImport
      parentRoute: typeof AuthedDealCopilotOpportunityIdRoute
    }
  }
}

interface AuthedDealCopilotOpportunityIdRouteChildren {
  AuthedDealCopilotOpportunityIdEditRoute: typeof AuthedDealCopilotOpportunityIdEditRoute
}

const AuthedDealCopilotOpportunityIdRouteChildren: AuthedDealCopilotOpportunityIdRouteChildren =
  {
    AuthedDealCopilotOpportunityIdEditRoute:
      AuthedDealCopilotOpportunityIdEditRoute,
  }

const AuthedDealCopilotOpportunityIdRouteWithChildren =
  AuthedDealCopilotOpportunityIdRoute._addFileChildren(
    AuthedDealCopilotOpportunityIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMarketplaceRoute: typeof AuthedMarketplaceRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedDealCopilotOpportunityIdRoute: typeof AuthedDealCopilotOpportunityIdRouteWithChildren
  AuthedDealCopilotNewRoute: typeof AuthedDealCopilotNewRoute
  AuthedProjectsNewRoute: typeof AuthedProjectsNewRoute
  AuthedTradesNewRoute: typeof AuthedTradesNewRoute
  AuthedTradesProfileRoute: typeof AuthedTradesProfileRoute
  AuthedDealCopilotIndexRoute: typeof AuthedDealCopilotIndexRoute
  AuthedProjectsIdAnalysisRoute: typeof AuthedProjectsIdAnalysisRoute
  AuthedProjectsIdEstimateRoute: typeof AuthedProjectsIdEstimateRoute
  AuthedProjectsIdReportRoute: typeof AuthedProjectsIdReportRoute
  AuthedProjectsIdScopeRoute: typeof AuthedProjectsIdScopeRoute
  AuthedProjectsIdUploadRoute: typeof AuthedProjectsIdUploadRoute
  AuthedTradesJobIdEditRoute: typeof AuthedTradesJobIdEditRoute
  AuthedProjectsIdIndexRoute: typeof AuthedProjectsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMarketplaceRoute: AuthedMarketplaceRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedDealCopilotOpportunityIdRoute:
    AuthedDealCopilotOpportunityIdRouteWithChildren,
  AuthedDealCopilotNewRoute: AuthedDealCopilotNewRoute,
  AuthedProjectsNewRoute: AuthedProjectsNewRoute,
  AuthedTradesNewRoute: AuthedTradesNewRoute,
  AuthedTradesProfileRoute: AuthedTradesProfileRoute,
  AuthedDealCopilotIndexRoute: AuthedDealCopilotIndexRoute,
  AuthedProjectsIdAnalysisRoute: AuthedProjectsIdAnalysisRoute,
  AuthedProjectsIdEstimateRoute: AuthedProjectsIdEstimateRoute,
  AuthedProjectsIdReportRoute: AuthedProjectsIdReportRoute,
  AuthedProjectsIdScopeRoute: AuthedProjectsIdScopeRoute,
  AuthedProjectsIdUploadRoute: AuthedProjectsIdUploadRoute,
  AuthedTradesJobIdEditRoute: AuthedTradesJobIdEditRoute,
  AuthedProjectsIdIndexRoute: AuthedProjectsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GalleryRouteChildren {
  GallerySlugRoute: typeof GallerySlugRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GallerySlugRoute: GallerySlugRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TradesRoute: TradesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  TradesJobIdRoute: TradesJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
