// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const _processEnv = typeof process !== "undefined" ? process.env : {};
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || _processEnv.SUPABASE_URL;
  // Accept both Lovable-style (PUBLISHABLE_KEY) and standard Supabase (ANON_KEY) names
  // so Vercel env vars set as VITE_SUPABASE_ANON_KEY work without code changes.
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    _processEnv.SUPABASE_PUBLISHABLE_KEY ||
    _processEnv.SUPABASE_ANON_KEY;

  console.log("[Supabase] init:", { urlSet: Boolean(SUPABASE_URL), keySet: Boolean(SUPABASE_PUBLISHABLE_KEY) });

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Wrap localStorage in a try/catch adapter so browser privacy settings
  // (e.g. Safari ITP, blocked third-party storage) never crash the app.
  const safeLocalStorage = {
    getItem(key: string): string | null {
      try {
        return typeof window !== "undefined" ? window.localStorage.getItem(key) : null;
      } catch {
        return null;
      }
    },
    setItem(key: string, value: string): void {
      try {
        if (typeof window !== "undefined") window.localStorage.setItem(key, value);
      } catch {
        // Blocked by browser privacy settings — session will not persist.
      }
    },
    removeItem(key: string): void {
      try {
        if (typeof window !== "undefined") window.localStorage.removeItem(key);
      } catch {
        // Blocked by browser privacy settings.
      }
    },
  };

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: safeLocalStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
