// @deprecated — Do not import the Supabase client from here.
// Use the service boundary instead:
//   import { supabase } from "@/services/supabase";
//
// This file is kept only for the generated Database types in ./types.ts
// (auto-generated by Supabase CLI; do not edit).
export { supabase } from "@/services/supabase";
